// Generates the imgui.hdll <-> hl-imgui binding surface from cimgui's own machine-readable API
// metadata (../third_party/cimgui/generator/output/*.json), instead of hand-writing every widget
// wrapper the way this repo's other native plugins do - ImGui's ~700-function public surface
// doesn't scale to that convention. Re-run this whenever third_party/{imgui,cimgui} are bumped
// (see third_party/VERSIONS.md); output is committed, not built on the fly.
//
// Emits:
//   native/src/generated/imgui_prims.cpp        - one HL_PRIM+DEFINE_PRIM per bindable function
//   hl-imgui/src/imgui/ImGui.hx                 - TWO things per bindable function, SPLICED into
//                                                 the hand-written abstract between marker comments
//                                                 (TYPEDEFS_START/END, METHODS_START/END below):
//                                                 a private @:hlNative extern (the real binding,
//                                                 never meant to be called directly - see
//                                                 emitImplLines) plus a public ergonomic dispatcher
//                                                 (see compileDispatcher) that hides cstr()/hl.Ref<T>/
//                                                 missing defaults and merges same-cimguiname
//                                                 overloads into one Haxe `overload` group where
//                                                 safe (see generatedMethodLines). Everything outside
//                                                 the markers is hand-written and survives
//                                                 regeneration untouched. One type, so a mod never
//                                                 has to import a second "raw bindings" class
//                                                 alongside the ergonomic one.
//   hl-imgui/src/imgui/Enums.hx                 - every ImGui*_ enum as an abstract Int
//   hl-imgui/src/imgui/Structs.hx               - POD structs actually referenced (ImVec2/ImVec4 + any other)
//                                                 (no "generated" subpackage for these two - once the
//                                                 bulk binding surface moved into ImGui.hx itself,
//                                                 the subpackage had nothing left to segregate; the
//                                                 files' own header comment already signals "don't
//                                                 hand-edit" on its own)
//
// Anything this generator can't safely express (variadic ..., va_list, raw callback pointers with
// no usable default, double pointers, templated/container types) is skipped and reported in the
// summary printed at the end - see SkipReason below.

import fs from 'node:fs'
import path from 'node:path'

const HERE = import.meta.dirname
const CIMGUI_DIR = path.join(HERE, '..', 'third_party', 'cimgui')
const OUT_CPP = path.join(HERE, '..', 'src', 'generated', 'imgui_prims.cpp')
// Top-level imgui package, not a "generated" subpackage - Enums.hx/Structs.hx are the only
// still-standalone generated files (everything else lives in ImGui.hx, see OUT_IMGUI_HX below), so
// a separate subpackage for "the generated stuff" no longer pulls its weight; the files' own
// "GENERATED - do not hand-edit" header comment already carries that signal on its own.
const OUT_HX_DIR = path.join(HERE, '..', '..', 'hl-imgui', 'src', 'imgui')
// The bulk binding surface is spliced directly into the hand-written imgui.ImGui abstract (between
// marker comments) rather than a separate imgui.generated.Native class - see this repo's own
// design discussion: Haxe has no partial classes and static members aren't inherited by a subclass
// name, so two classes was a real "which one do I import" problem for a mod author. One file, one
// importable type; regeneration only ever rewrites the text between each marker pair.
const OUT_IMGUI_HX = path.join(HERE, '..', '..', 'hl-imgui', 'src', 'imgui', 'ImGui.hx')
// Module-level (no indent) - typedefs can't live inside the abstract body.
const TYPEDEFS_START = '// >>> GENERATED TYPEDEFS by native/codegen/generate.mts below - do not hand-edit, re-run the generator instead. >>>'
const TYPEDEFS_END = '// <<< END GENERATED TYPEDEFS <<<'
// Indented one tab - these ARE members of the abstract body.
const METHODS_START = '\t// >>> GENERATED by native/codegen/generate.mts below this point - do not hand-edit, re-run the generator instead. >>>'
const METHODS_END = '\t// <<< END GENERATED <<<'

interface ArgT {
  name: string
  type: string
}

interface FuncDef {
  args: string
  argsT: ArgT[]
  cimguiname: string
  constructor?: boolean
  defaults: Record<string, string>
  funcname: string
  isvararg?: string
  location: string
  namespace: string
  nonUDT?: number
  ov_cimguiname: string
  ret?: string
  templated?: boolean
  stname: string
}

interface StructsAndEnums {
  enums: Record<string, { name: string; value: string; calc_value: number }[]>
  enumtypes: Record<string, string>
  nonPOD: Record<string, boolean>
  structs: Record<string, { name: string; type: string }[]>
}

const definitions: Record<string, FuncDef[]> = JSON.parse(
  fs.readFileSync(path.join(CIMGUI_DIR, 'generator', 'output', 'definitions.json'), 'utf8'),
)
const structsAndEnums: StructsAndEnums = JSON.parse(
  fs.readFileSync(path.join(CIMGUI_DIR, 'generator', 'output', 'structs_and_enums.json'), 'utf8'),
)
const typedefsDict: Record<string, string> = JSON.parse(
  fs.readFileSync(path.join(CIMGUI_DIR, 'generator', 'output', 'typedefs_dict.json'), 'utf8'),
)

// ---------------------------------------------------------------------------
// Type resolution
// ---------------------------------------------------------------------------

// Hardcoded, not discoverable from structs_and_enums.json's own `structs` dict - cimgui treats
// ImVec2/ImVec4 as fundamental built-in value types (declared directly in cimgui.h as
// ImVec2_c/ImVec4_c), not as parsed user structs like everything else in that dict.
const HARDCODED_POD_STRUCTS: Record<string, { name: string; type: string }[]> = {
  ImVec2: [
    { name: 'x', type: 'float' },
    { name: 'y', type: 'float' },
  ],
  ImVec4: [
    { name: 'x', type: 'float' },
    { name: 'y', type: 'float' },
    { name: 'z', type: 'float' },
    { name: 'w', type: 'float' },
  ],
}

type PrimKind = 'void' | 'bool' | 'i32' | 'i64' | 'f32' | 'f64'

const PRIMITIVES: Record<string, PrimKind> = {
  void: 'void',
  bool: 'bool',
  float: 'f32',
  double: 'f64',
  int: 'i32',
  'unsigned int': 'i32',
  short: 'i32',
  'unsigned short': 'i32',
  'signed char': 'i32',
  'unsigned char': 'i32',
  char: 'i32',
  long: 'i32',
  'unsigned long': 'i32',
  size_t: 'i64',
  ImS8: 'i32',
  ImU8: 'i32',
  ImS16: 'i32',
  ImU16: 'i32',
  ImS32: 'i32',
  ImU32: 'i32',
  ImS64: 'i64',
  ImU64: 'i64',
  int64_t: 'i64',
  uint64_t: 'i64',
  'long long': 'i64',
  'unsigned long long': 'i64',
}

const PRIM_HL_DEFINE: Record<PrimKind, string> = {
  void: '_VOID',
  bool: '_BOOL',
  i32: '_I32',
  i64: '_I64',
  f32: '_F32',
  f64: '_F64',
}

const PRIM_HX_TYPE: Record<PrimKind, string> = {
  void: 'Void',
  bool: 'Bool',
  i32: 'Int',
  i64: 'hl.I64',
  f32: 'Single',
  f64: 'Float',
}

const PRIM_C_TYPE: Record<PrimKind, string> = {
  void: 'void',
  bool: 'bool',
  i32: 'int',
  i64: 'int64_t',
  f32: 'float',
  f64: 'double',
}

// One entry per distinct opaque handle / POD struct actually referenced by a bound function -
// populated while resolving, then emitted once each (avoids dead types for the ~85 nonPOD names
// and ~40 POD struct names that exist in cimgui's metadata but nothing bindable ever touches).
const referencedOpaqueTypes = new Set<string>()
const referencedPodStructs = new Set<string>()

type Resolved =
  | { kind: 'prim'; prim: PrimKind }
  | { kind: 'string'; mutable: boolean } // char* / const char* - mutable (no const) means a genuine
  // caller-owned OUTPUT buffer (e.g. InputText's buf, which ImGui writes into) rather than a
  // read-only label/text value - never safe to auto-convert to a Haxe String (see compileDispatcher)
  | { kind: 'opaque'; name: string } // pointer to a nonPOD type -> hl.Abstract handle
  | { kind: 'struct'; name: string } // pointer to a POD struct (by-value at the real call site) -> _STRUCT
  | { kind: 'ref'; prim: PrimKind } // single-scalar T* (not char, not array) -> hl.Ref<T> / _REF
  | { kind: 'bytes' } // generic pointer / fixed array -> hl.Bytes / _BYTES
  | { kind: 'unsupported'; reason: string }

function rawPodStructFields(name: string): { name: string; type: string }[] | null {
  if (HARDCODED_POD_STRUCTS[name]) return HARDCODED_POD_STRUCTS[name]
  if (structsAndEnums.structs[name] && !structsAndEnums.nonPOD[name]) return structsAndEnums.structs[name]
  return null
}

// A struct field's type, resolved ONLY against the flat primitive table - deliberately not the
// full resolveBase (which handles pointers/nested structs/opaque handles too) since a Haxe
// @:struct mirror can only safely reproduce plain scalar fields at fixed offsets.
function primFieldKind(rawType: string): PrimKind | null {
  let t = rawType.trim()
  if (t.startsWith('const ')) t = t.slice('const '.length).trim()
  if (t.endsWith('*') || t.includes('[')) return null
  const prim = PRIMITIVES[t]
  return prim !== undefined ? prim : null
}

// A POD struct is only safe to mirror in Haxe if it has an all-primitive field list - our
// generated wrapper always hands the real native function a pointer to whatever memory Haxe
// allocated for the @:struct instance; if even one field were silently dropped (instead of just
// skipping the whole struct), the Haxe allocation would be smaller than - and every field after
// the gap misaligned with - the real native struct's actual layout, and the native side would
// read/write past the end of (or into the wrong bytes of) that undersized allocation. Structs that
// fail this check are treated as unsupported everywhere, not partially mirrored.
const fullyPrimitiveCache = new Map<string, { name: string; prim: PrimKind }[] | null>()
function fullyPrimitiveStructFields(name: string): { name: string; prim: PrimKind }[] | null {
  if (fullyPrimitiveCache.has(name)) return fullyPrimitiveCache.get(name)!
  const raw = rawPodStructFields(name)
  let result: { name: string; prim: PrimKind }[] | null = null
  if (raw) {
    const resolved: { name: string; prim: PrimKind }[] = []
    let allPrimitive = true
    for (const f of raw) {
      const prim = primFieldKind(f.type)
      if (prim === null) {
        allPrimitive = false
        break
      }
      resolved.push({ name: f.name, prim })
    }
    if (allPrimitive) result = resolved
  }
  fullyPrimitiveCache.set(name, result)
  return result
}

// Resolves a single argT.type / ret string down to something we know how to marshal, following
// typedefs_dict.json aliases (ImGuiID -> unsigned int, ImGuiWindowFlags -> int, ...) until a
// primitive/pointer/known-struct form is reached, or giving up after a few hops.
function resolveBase(rawType: string, depth = 0): Resolved {
  let t = rawType.trim()
  const isConst = t.startsWith('const ')
  if (isConst) t = t.slice('const '.length).trim()

  if (t === 'va_list' || t.includes('(*)') || t.endsWith(')')) {
    return { kind: 'unsupported', reason: `callback/function-pointer type "${rawType}"` }
  }

  // Fixed-size array, e.g. "float[2]" - same marshaling as a generic pointer (caller writes/reads
  // N contiguous elements); the element count isn't tracked past this point.
  const arrayMatch = t.match(/^(.+)\[\d+\]$/)
  if (arrayMatch) {
    const elemPrim = PRIMITIVES[arrayMatch[1].trim()]
    if (elemPrim !== undefined) return { kind: 'bytes' }
    return { kind: 'unsupported', reason: `array of unresolved element type "${rawType}"` }
  }

  // Double (or higher) pointers - only a handful of real call sites (e.g. "const char* const*"
  // string-array params) and not worth the marshaling complexity here.
  if ((t.match(/\*/g) ?? []).length >= 2) {
    return { kind: 'unsupported', reason: `multi-level pointer "${rawType}"` }
  }

  const isPointer = t.endsWith('*')
  const base = isPointer ? t.slice(0, -1).trim() : t

  if (isPointer && (base === 'char' || base === 'void')) {
    // char* / const char* -> string-ish byte buffer. void* has no safe generic Haxe shape, so it
    // only survives if the call site drops it via a default (see resolveArg) - otherwise unsupported.
    return base === 'char' ? { kind: 'string', mutable: !isConst } : { kind: 'unsupported', reason: 'void*' }
  }

  // POD structs (ImVec2, ImVec4, ...) passed BY VALUE - cimgui's argsT already strips references
  // down to a plain value type for these (e.g. Button's `size` arrives as "const ImVec2", no "*"
  // at all), and "ret" fields for by-value returns instead use cimgui's own "_c"-suffixed mirror
  // name directly, ALSO with no trailing "*" (e.g. igGetWindowSize's ret is "ImVec2_c" - confirmed
  // against cimgui.h itself). Both spellings resolve to the same struct: our generated wrapper
  // always takes a pointer at the HL boundary (matching this repo's existing _STRUCT convention)
  // and dereferences it to get the by-value copy the real cimgui call expects.
  //
  // Deliberately gated on `!isPointer` - a POINTER-form occurrence of one of these names (e.g.
  // ImDrawList_AddPolyline's `const ImVec2* points`, a genuine multi-element array, or
  // igIsMousePosValid's nullable `const ImVec2* mouse_pos`) is NOT safe to dereference-and-pass-
  // by-value; both cases are real, confirmed by a real MSVC build (the array case would've
  // silently passed only the first point; the nullable case can't be dereferenced at all when
  // null). Pointer-form falls through to the generic 'bytes' pointer handling below instead.
  //
  // Checked BEFORE the nonPOD/opaque branch below: cimgui's own nonPOD dict marks ImVec2/ImVec4
  // (and other HARDCODED_POD_STRUCTS entries) nonPOD:true too (it means "not safe to memcpy given
  // its full API", not "never appears by value") - some *other* function takes one of these by
  // value, which would otherwise never reach this branch and collide with the exact same name
  // resolving to an opaque handle elsewhere (two conflicting Haxe type declarations for one name).
  // Our own value-mirroring choice for these specific names always wins for the by-value case.
  if (!isPointer) {
    const podBase = base.endsWith('_c') && !fullyPrimitiveStructFields(base) ? base.slice(0, -2) : base
    if (fullyPrimitiveStructFields(podBase)) {
      referencedPodStructs.add(podBase)
      return { kind: 'struct', name: podBase }
    }
  }

  if (isPointer && structsAndEnums.nonPOD[base]) {
    // Pointer-form HARDCODED_POD_STRUCTS names (see the by-value branch's own comment above) must
    // NOT fall into the opaque-handle path just because cimgui's nonPOD dict also marks them true -
    // that would collide with the exact same name's by-value struct declaration elsewhere. Generic
    // 'bytes' handles a raw pointer to arbitrary Vec2/Vec4 data (single nullable value or a whole
    // array) equally well; cCastTarget below adds the "_c" suffix cimgui.h's real signature needs.
    if (!HARDCODED_POD_STRUCTS[base]) {
      referencedOpaqueTypes.add(base)
      return { kind: 'opaque', name: base }
    }
  }

  // Pointer-form occurrence of a HARDCODED_POD_STRUCTS name (see the by-value branch above) -
  // falls all the way down here rather than being caught earlier since it's neither a by-value
  // struct nor (as of the check just above) treated as an opaque handle. A generic raw pointer,
  // same as any other 'bytes' case - covers both a genuine array (ImDrawList_AddPolyline's
  // `points`) and a single nullable value (igIsMousePosValid's `mouse_pos`) equally.
  if (isPointer && HARDCODED_POD_STRUCTS[base]) return { kind: 'bytes' }

  const prim = PRIMITIVES[base]
  if (prim !== undefined) {
    if (!isPointer) return { kind: 'prim', prim }
    // Single pointer to a primitive (bool* p_open, float* v, int* v, ...) - a genuine single-value
    // in/out parameter, exactly what HL's own _REF(t)/hl.Ref<T> mechanism exists for (already used
    // in this repo's dx12 proxy for `int* a4` params).
    return { kind: 'ref', prim }
  }

  // Bare non-pointer nonPOD value should never occur (cimgui never passes these by value - only
  // POD structs, handled above, get by-value treatment), but guard rather than mis-marshal it.
  if (!isPointer && structsAndEnums.nonPOD[base]) {
    return { kind: 'unsupported', reason: `by-value non-primitive "${rawType}"` }
  }

  // Unrecognized name - chase typedefs_dict.json's alias chain (ImGuiID -> unsigned int, ...) and,
  // failing that, structs_and_enums.json's enumtypes dict (ImGuiKey -> int, ImGuiDir -> int, ImGui-
  // SortDirection -> ImU8, ...) a few hops before giving up. Some flag/enum "value holder" types
  // (ImGuiWindowFlags, ImGuiKey, ...) are plain int typedefs by Dear ImGui's own convention
  // specifically so they convert to/from a raw int with no cast needed - which is exactly why
  // resolving them down to a bare `_I32`/Int here, with no separate enum-typed C parameter, works.
  if (depth < 6) {
    const aliasTarget = (typedefsDict[base] ?? structsAndEnums.enumtypes[base])?.replace(/^struct\s+/, '').trim()
    if (aliasTarget && aliasTarget !== rawType && aliasTarget !== t) {
      return resolveBase(isPointer ? `${aliasTarget}*` : aliasTarget, depth + 1)
    }
  }

  return { kind: 'unsupported', reason: `unresolved type "${rawType}"` }
}

// ---------------------------------------------------------------------------
// Function selection
// ---------------------------------------------------------------------------

interface BoundArg {
  name: string
  resolved: Resolved
}

interface BoundFunc {
  def: FuncDef
  args: BoundArg[]
  ret: Resolved
  outParam?: Resolved // set when nonUDT return -> appended out-pointer arg instead of a real return
}

// See this set's own usage below (in the function-selection loop) for why each entry is here -
// confirmed by a real MSVC build, not guessed; re-check against a fresh build after bumping the
// vendored ImGui/cimgui version in case cimgui's own declarations change.
const MANUAL_SKIP = new Set(['ImDrawList_AddText_FontPtr', 'ImFont_RenderChar'])

// Bare `T*` args that are semantically arrays, not the genuine single-scalar in/out values
// resolveBase's default 'ref' handling assumes for any pointer-to-primitive - it can't tell the
// difference from the type string alone (a fixed-size array like `float[4]` would resolve to 'bytes'
// automatically, but a bare pointer with no array size, and no `[N]` suffix, never does). Confirmed
// against real ImGui/cimgui headers, not guessed - each entry's own reason:
//  - ColorPicker4's ref_col is a 4-element color swatch buffer, same shape as this function's own
//    `col` param.
//  - PlotLines/PlotHistogram's `values` is the whole graph's float array (paired with a
//    `values_count` sibling - the actual tell that gave this one away).
//  - ImFontAtlas's two glyph_ranges params, and ImFontGlyphRangesBuilder_AddRanges's `ranges`, are
//    each a null-terminated ImWchar range-pairs array (no count sibling at all - terminated by a
//    trailing 0,0 pair instead), not a single ImWchar.
// Keyed "ov_cimguiname.argName" - forces that one arg down the same 'bytes' path a genuine array
// param already takes, instead of the default single-scalar 'ref' path (which would otherwise
// wrongly offer a FloatRef/IntRef in the auto-generated dispatcher - see compileDispatcher below).
const FORCE_BYTES_ARGS = new Set([
  'igColorPicker4.ref_col',
  'igPlotLines_FloatPtr.values',
  'igPlotHistogram_FloatPtr.values',
  'ImFontAtlas_AddFontFromFileTTF.glyph_ranges',
  'ImFontAtlas_AddFontFromMemoryCompressedBase85TTF.glyph_ranges',
  'ImFontGlyphRangesBuilder_AddRanges.ranges',
])

const skipped: { name: string; reason: string }[] = []
const bound: BoundFunc[] = []

for (const overloads of Object.values(definitions)) {
  for (const def of overloads) {
    // Only the public API (imgui.h itself) - imgui_internal/imgui_freetype entries are unstable,
    // undocumented, and not meant for anything outside ImGui's own source tree.
    if (!def.location.startsWith('imgui:')) continue
    // Free functions (namespace "ImGui") or methods on a type we expose as an opaque handle
    // (namespace == that type's name, e.g. "ImDrawList") - anything else (methods on structs we
    // don't bind, like the stb_* internals) is out of scope.
    const isFreeFunction = def.namespace === 'ImGui'
    const isBoundStructMethod = def.namespace === def.stname && structsAndEnums.nonPOD[def.namespace]
    if (!isFreeFunction && !isBoundStructMethod) continue
    if (def.isvararg) {
      skipped.push({ name: def.ov_cimguiname, reason: 'variadic (...)' })
      continue
    }
    // Methods on a generic template (ImVector<T>, ImChunkStream<T>, ImPool<T>, ...) - cimgui's own
    // JSON flags these `templated: true`, and for good reason: "ImVector_clear"/"ImVector_capacity"/
    // etc. have no concrete instantiation and no real linkable symbol (confirmed by a real MSVC
    // build - every one failed as "identifier not found"), unlike a genuinely bound struct method
    // (whose stname is always a concrete type, e.g. "ImDrawList").
    if (def.templated) {
      skipped.push({ name: def.ov_cimguiname, reason: 'generic template method (no concrete instantiation)' })
      continue
    }
    // A handful of cimgui.h declarations use the REAL (non-"_c") ImVec2/ImVec4 type for a pointer
    // parameter instead of the usual "_c"-suffixed mirror (confirmed inconsistent by a real MSVC
    // build - most pointer-form Vec2/Vec4 params DO want the "_c" mirror, e.g. igIsMousePosValid's
    // mouse_pos, but these two specifically don't) - nothing in cimgui's JSON metadata
    // distinguishes the two cases, so rather than risk silently mis-casting elsewhere, these two are
    // named explicitly and skipped.
    if (MANUAL_SKIP.has(def.ov_cimguiname)) {
      skipped.push({ name: def.ov_cimguiname, reason: 'manually excluded (see MANUAL_SKIP)' })
      continue
    }
    // Constructors (`stname X, cimguiname X_X`) have no plain-forwarding call shape - cimgui
    // itself special-cases these as placement-new/IM_NEW, not an ordinary free-function call - and
    // correspondingly omit "ret" entirely, which a generic forwarding wrapper can't do anything
    // sensible with either way. `constructor` is a real, explicitly-set JSON key when present -
    // checking truthiness directly on `def` would always be true, since every plain object
    // inherits a non-own `constructor` property from Object.prototype.
    if (Object.prototype.hasOwnProperty.call(def, 'constructor') || def.ret === undefined) {
      skipped.push({ name: def.ov_cimguiname, reason: 'constructor (no plain-call shape)' })
      continue
    }

    const args: BoundArg[] = []
    let dropped = false
    for (const a of def.argsT) {
      let resolved = resolveBase(a.type)
      if (resolved.kind === 'ref' && FORCE_BYTES_ARGS.has(`${def.ov_cimguiname}.${a.name}`)) resolved = { kind: 'bytes' }
      if (resolved.kind === 'unsupported') {
        if (a.name in def.defaults) {
          // Unsupported but defaulted (callback/user_data with a NULL default, typically) - drop
          // it from the exposed signature and hardcode the default in the generated call instead
          // of losing the whole function over one param nothing calls non-default anyway.
          continue
        }
        dropped = true
        skipped.push({ name: def.ov_cimguiname, reason: `arg "${a.name}": ${resolved.reason}` })
        break
      }
      args.push({ name: a.name, resolved })
    }
    if (dropped) continue

    const retResolved = resolveBase(def.ret!)
    if (retResolved.kind === 'unsupported') {
      skipped.push({ name: def.ov_cimguiname, reason: `return: ${retResolved.reason}` })
      continue
    }
    // hl.Ref<T> is an in/out PARAMETER convention, never valid as a return - a bare "T*" return
    // (rare) has no single-value semantics to preserve, so treat it as a generic pointer instead.
    const ret: Resolved = retResolved.kind === 'ref' ? { kind: 'bytes' } : retResolved

    let outParam: Resolved | undefined
    let finalRet = ret
    if (def.nonUDT === 1 && (ret.kind === 'struct' || ret.kind === 'opaque')) {
      // By-value struct return (ImVec2/ImVec4/...) - cimgui's C ABI really does return these by
      // value (confirmed against cimgui.h directly), which DEFINE_PRIM has no return kind for.
      // Turn it into a caller-allocated out-pointer parameter instead, void return.
      outParam = ret
      finalRet = { kind: 'prim', prim: 'void' }
    }

    bound.push({ def, args, ret: finalRet, outParam })
  }
}

// ---------------------------------------------------------------------------
// Emit: native/src/generated/imgui_prims.cpp
// ---------------------------------------------------------------------------

// cimgui.h only gives ImVec2/ImVec4 (and a couple of others we never bind, e.g. ImColor) a
// separate by-value-safe mirror struct suffixed "_c" (ImVec2_c) - every other POD struct
// (ImDrawVert, ...) is emitted under its real, unsuffixed name directly. The Haxe-facing name
// (and Structs.hx's class name) is always the plain upstream name either way - this suffix is a
// native-side-only detail of which real cimgui.h type our generated wrapper dereferences into.
const CIMGUI_VALUE_MIRROR_SUFFIXED = new Set(['ImVec2', 'ImVec4'])

function structCType(name: string): string {
  return CIMGUI_VALUE_MIRROR_SUFFIXED.has(name) ? `${name}_c` : name
}

function cParamType(r: Resolved): string {
  switch (r.kind) {
    case 'prim':
      return PRIM_C_TYPE[r.prim]
    case 'string':
      return 'vbyte*'
    case 'opaque':
      return `${r.name}*`
    case 'struct':
      return `${structCType(r.name)}*`
    case 'ref':
      return `${PRIM_C_TYPE[r.prim]}*`
    case 'bytes':
      return 'vbyte*'
    case 'unsupported':
      throw new Error('unreachable')
  }
}

function cDefineMacro(r: Resolved): string {
  switch (r.kind) {
    case 'prim':
      return PRIM_HL_DEFINE[r.prim]
    case 'string':
      return '_BYTES'
    case 'opaque':
      return `_ABSTRACT(${r.name})`
    case 'struct':
      // Pointer to a Haxe @:struct instance (Structs.hx), matching this repo's existing
      // shader-cache/native/src/sc/native/pso convention for passing POD structs by pointer.
      return '_STRUCT'
    case 'ref':
      return `_REF(${PRIM_HL_DEFINE[r.prim]})`
    case 'bytes':
      return '_BYTES'
    case 'unsupported':
      throw new Error('unreachable')
  }
}

// The real cimgui parameter type for one argument, as a C-style cast target: strips a fixed-size
// array down to its decayed pointer form ("float[2]" -> "float*", matching how an array-typed C++
// parameter is actually received), otherwise used verbatim. Needed because our own wrapper's
// declared parameter type (cParamType) is often only "close enough" to what the real function
// actually expects - a generic byte pointer standing in for a typed array, or a plain `int`
// standing in for a genuine `enum ImGuiKey`-typed parameter (Dear ImGui's *Flags types are plain
// `int` typedefs specifically so a bare int converts with no cast, but non-flag enums like
// ImGuiKey/ImGuiSortDirection are real distinct enum types, confirmed by real MSVC build errors -
// "cannot convert argument 1 from 'int' to 'ImGuiKey'" - not something the cimgui JSON metadata
// flags up front either way, since it normalizes both cases down to the same "int"-family shape).
function cCastTarget(rawType: string): string {
  let t = rawType.trim()
  const arrayMatch = t.match(/^(.+)\[\d+\]$/)
  if (arrayMatch) t = `${arrayMatch[1].trim()}*`
  // Pointer-form ImVec2*/ImVec4* (an array, or a single nullable value - see resolveBase's
  // isPointer-gated struct check) needs cimgui.h's real "_c"-suffixed type, same substitution
  // structCType applies for the by-value case.
  for (const name of CIMGUI_VALUE_MIRROR_SUFFIXED) {
    t = t.replace(new RegExp(`\\b${name}\\b`, 'g'), `${name}_c`)
  }
  return t
}

// The literal C expression forwarded to the real cimgui call for one bound argument. rawType is
// the argument's ORIGINAL (pre-resolution) type text from cimgui's own JSON, used only to compute
// the cast target above - kept separate from Resolved so the resolver itself doesn't need to carry
// unrelated bookkeeping just for this.
function callExpr(name: string, r: Resolved, rawType: string): string {
  switch (r.kind) {
    case 'string':
      // Plain `char*`, not `const char*` - some string-kind params are genuinely writable (e.g.
      // igInputText's `buf`, which ImGui writes the edited text into), and `char*` converts
      // implicitly to a `const char*` parameter anyway, so this one cast covers both.
      return `(char*)${name}`
    case 'struct':
      return `*${name}`
    case 'opaque':
      return name
    case 'prim':
    case 'ref':
    case 'bytes':
      // Harmless no-op when our wrapper's own declared type already matches exactly (the common
      // case); required whenever it's only an approximation (see this function's own comment).
      return `(${cCastTarget(rawType)})${name}`
    case 'unsupported':
      throw new Error('unreachable')
  }
}

// A function bound with one or more `ref`-kind args (hl.Ref<T>/_REF(T)) gets a second exported
// variant alongside the normal one: every ref arg becomes a plain `bytes`-kind arg instead (raw
// hl.Bytes/vbyte*, no other change - callExpr's cast is driven by the ORIGINAL cimgui type text,
// not by this Resolved kind, so the real native call is byte-for-byte identical either way). HL's
// hl.Ref only ever addresses a stack slot in the CALLER's own frame (see hl-imgui/README.md's
// "Persisting widget state in a field") - useless for a caller that wants to hold the value in a
// field across frames. hl.Bytes is a real heap pointer instead: freely storable, and stable across
// calls since HL's GC never moves live allocations. Named "<name>_Ptr" - cimgui itself never
// produces a name ending that way, so it can't collide with a real overload suffix.
function hasRefArg(f: BoundFunc): boolean {
  return f.args.some((a) => a.resolved.kind === 'ref')
}

function toPointerVariantArgs(args: BoundArg[]): BoundArg[] {
  return args.map((a) => (a.resolved.kind === 'ref' ? { name: a.name, resolved: { kind: 'bytes' } as Resolved } : a))
}

function pointerVariantName(f: BoundFunc): string {
  return `${f.def.ov_cimguiname}_Ptr`
}

// Free ImGui:: functions (never struct methods) always start with "ig" in cimgui's own naming
// (confirmed by every ov_cimguiname/cimguiname seen so far) - stripping it and lowercasing the new
// first letter turns "igCheckbox"/"igOpenPopup_Str" into "checkbox"/"openPopup_Str". Struct methods
// (ImDrawList_AddText, ImFontAtlas_AddFont, ...) deliberately keep their full raw name unstripped -
// unlike free functions, stripping their receiver-type prefix risks real collisions (many different
// struct types share common method names like Clear/Reset), and the prefix already makes them
// legible without it.
function cleanFreeFunctionName(rawName: string): string {
  const stripped = rawName.replace(/^ig/, '')
  return stripped.charAt(0).toLowerCase() + stripped.slice(1)
}

// cimgui's own snake_case param names (str_id, popup_flags, v_min, ...) turned into idiomatic Haxe
// camelCase for the PUBLIC dispatcher layer (see compileDispatcher below) - purely cosmetic, @:hlNative
// externs bind by position not name, so this has zero effect on the actual native call.
function toCamelCase(name: string): string {
  return name.replace(/_([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())
}

// Maps a ref-kind PrimKind to the hand-written persistent-pointer wrapper type (imgui/ref/*.hx) that
// should appear in the PUBLIC dispatcher signature instead of a raw hl.Ref<T> - see
// imgui.ref.BoolRef's own doc comment for why hl.Ref<T> itself is never safe to expose to a mod
// author (it only writes back to a genuine local at the call site, never to a field, so a caller
// storing state in a field - the normal case, to persist it across frames - silently wouldn't work).
const REF_WRAPPER_TYPE: { [K in PrimKind]?: string } = {
  bool: 'BoolRef',
  i32: 'IntRef',
  f32: 'FloatRef',
  f64: 'DoubleRef',
}

// A single numeric C++ literal ("-FLT_MIN", "0.0f", "+360.0f", ...) down to plain Haxe source. FLT_MIN
// only ever shows up negated in cimgui's own defaults (ProgressBar's sentinel "fill remaining width"
// size) - not worth a general constant table for the one macro that occurs, so it's hardcoded here.
// A small set of raw sizeof() results actually seen in cimgui's own defaults (PlotLines/PlotHistogram's
// `stride = sizeof(float)`) - not a general C sizeof evaluator, just enough named types to translate
// the handful that occur; anything else falls through translateDefault's final `return null`.
const SIZEOF_BYTES: Record<string, number> = { float: 4, int: 4, double: 8, short: 2, char: 1 }

function numLit(raw: string): string {
  let t = raw.trim().replace(/f$/i, '')
  if (t.startsWith('+')) t = t.slice(1)
  if (t === '-FLT_MIN') return '-1.1754943508222875e-38'
  if (t === 'FLT_MAX' || t === '-FLT_MAX') return `${t.startsWith('-') ? '-' : ''}3.4028234663852886e+38`
  const sizeofM = t.match(/^sizeof\((\w+)\)$/)
  if (sizeofM && SIZEOF_BYTES[sizeofM[1]] !== undefined) return String(SIZEOF_BYTES[sizeofM[1]])
  return t
}

// Translates one cimgui JSON default-value literal (raw C++ source text, e.g. `"%.3f"`, `0.0f`,
// `NULL`, `ImVec2(-FLT_MIN,0)`) into either a Haxe constant expression usable directly as the
// parameter's own default (`literal`), or a signal that the param needs a nullable default PLUS a
// `param = param ?? vec2(x, y)` coalesce statement in the dispatcher body instead (`structNew` -
// Haxe parameter defaults must be compile-time constants, so a struct constructor call like cimgui's
// own "ImVec2(-FLT_MIN,0)" can't be one - the actual x/y/z/w literals are carried through via `ctor`
// rather than always coalescing to a blank (0,0), so a real sentinel default like ProgressBar's isn't
// silently lost). Returns null when the literal can't be safely translated - leaves the Haxe param
// required rather than guessing wrong.
type DefaultInfo = { kind: 'literal'; text: string } | { kind: 'structNew'; ctor: string } | null
function translateDefault(raw: string): DefaultInfo {
  const t = raw.trim()
  if (t === 'NULL' || t === 'nullptr') return { kind: 'literal', text: 'null' }
  if (t === 'true' || t === 'false') return { kind: 'literal', text: t }
  if (/^".*"$/.test(t)) return { kind: 'literal', text: t }
  const vec2m = t.match(/^ImVec2\(\s*([^,]+?)\s*,\s*([^,]+?)\s*\)$/)
  if (vec2m) return { kind: 'structNew', ctor: `vec2(${numLit(vec2m[1])}, ${numLit(vec2m[2])})` }
  const vec4m = t.match(/^ImVec4\(\s*([^,]+?)\s*,\s*([^,]+?)\s*,\s*([^,]+?)\s*,\s*([^,]+?)\s*\)$/)
  if (vec4m) return { kind: 'structNew', ctor: `vec4(${numLit(vec4m[1])}, ${numLit(vec4m[2])}, ${numLit(vec4m[3])}, ${numLit(vec4m[4])})` }
  if (/^[+-]?[\d.]+f?$/i.test(t) || /^[+-]?(FLT_MAX|FLT_MIN)$/.test(t) || /^sizeof\(\w+\)$/.test(t)) {
    return { kind: 'literal', text: numLit(t) }
  }
  return null
}

// Real cimgui overloads of ONE conceptual function collapse to distinctly-suffixed exported symbols
// (igOpenPopup_Str/igOpenPopup_ID, ...), grouped under a shared `cimguiname` in definitions.json. When
// every member's PUBLIC dispatcher signature (see compileDispatcher) ends up mutually distinguishable,
// they merge into one `overload extern inline` group under that shared name instead of each keeping
// its own suffix - exactly what a mod author would write by hand. "Distinguishable" means no two
// members produce the exact same ordered parameter-type list - Haxe accepts prefix-style overlaps
// (one signature's types being a prefix of another's, e.g. via a trailing optional arg) just fine,
// resolving by best match at each call site, but hard-errors on a literal duplicate (confirmed by a
// real compile test: "Another overloaded field of same signature was already declared").
function signatureKey(params: { hxType: string }[]): string {
  return params.map((p) => p.hxType).join(',')
}

// text_begin/text_end (and str/str_end, str_id_begin/str_id_end, ...) is a substring-of-ONE-buffer
// idiom in real ImGui (pointer arithmetic into a single C string), not two independent strings - no
// pair of managed Haxe Strings can express that. These wrappers only cover the overwhelmingly common
// whole-string case: the "_end" half of a detected pair is dropped from the dispatcher's exposed
// params entirely (hardcoded null in the real call, meaning "read until the embedded terminator"),
// and if the "begin" half is literally named "X_begin", it's exposed under the simplified name "X".
function computeStringPairDrops(args: BoundArg[]): { dropNames: Set<string>; renameTo: Map<string, string> } {
  // Mutable (non-const) buffers are never one half of a begin/end pair in practice (a writable
  // buffer like InputText's buf always appears alone) - excluded so a hypothetical future one
  // couldn't be mistaken for the read-only end of some other arg's pair.
  const stringNames = new Set(args.filter((a) => a.resolved.kind === 'string' && !a.resolved.mutable).map((a) => a.name))
  const dropNames = new Set<string>()
  const renameTo = new Map<string, string>()
  for (const a of args) {
    if (a.resolved.kind !== 'string' || a.resolved.mutable || !a.name.endsWith('_end')) continue
    const base = a.name.slice(0, -'_end'.length)
    if (stringNames.has(base)) {
      dropNames.add(a.name)
    } else if (stringNames.has(`${base}_begin`)) {
      dropNames.add(a.name)
      renameTo.set(`${base}_begin`, base)
    }
  }
  return { dropNames, renameTo }
}

interface DispatcherParam {
  hxName: string
  hxType: string
  defaultLiteral: string | null // null = required
}

interface CompiledDispatcher {
  implName: string // always private - see compileDispatcher
  implLines: string[]
  params: DispatcherParam[]
  preStatements: string[] // struct-default coalesce lines, run before the real call
  callArgs: string[]
  retType: string
  returnsCoalescedOut: string | null // param name to `return` after the call (struct outParam upgrade)
  fallbackPublicName: string // used when not merged into an overload group (or single-member group)
  groupKey: string | null // cimguiname - only set for free (namespace 'ImGui') functions
}

// Builds everything needed to emit ONE bound function: the real @:hlNative-bound implementation
// (always private and named `_xxx` - never meant to be called directly by a mod author, only by the
// dispatcher below) and the ergonomic PUBLIC dispatcher that hides every remaining friction point a
// mod author would otherwise hit - cstr() for string args (computeStringPairDrops above), hl.Ref<T>'s
// field-unsafety for ref args (REF_WRAPPER_TYPE above), and missing default values for anything
// cimgui's own JSON declares one for (translateDefault above). A ref-arg function only ever gets ONE
// dispatcher, over the hl.Bytes-backed persistent ("_Ptr") form - the raw hl.Ref<T> form is skipped
// entirely (see the call site below), since nothing should ever call it from Haxe.
function compileDispatcher(f: BoundFunc, usedImplNames: Set<string>): CompiledDispatcher {
  const isFree = f.def.namespace === 'ImGui'
  const hasRef = hasRefArg(f)
  const implArgs = hasRef ? toPointerVariantArgs(f.args) : f.args
  const implExportName = hasRef ? pointerVariantName(f) : f.def.ov_cimguiname
  const implCleanName = isFree ? cleanFreeFunctionName(implExportName) : implExportName
  const implName = `_${implCleanName}`
  if (usedImplNames.has(implName)) throw new Error(`duplicate impl name: ${JSON.stringify(implName)}`)
  usedImplNames.add(implName)
  const implLines = emitImplLines(implName, implArgs, implExportName, f)

  const { dropNames, renameTo } = computeStringPairDrops(f.args)
  const params: DispatcherParam[] = []
  const preStatements: string[] = []
  const callArgs: string[] = []

  for (let i = 0; i < implArgs.length; i++) {
    const arg = implArgs[i]
    const origResolved = f.args[i].resolved
    if (dropNames.has(arg.name)) {
      callArgs.push('null')
      continue
    }

    // cimgui's own Hungarian-notation "p_" prefix on ref/out params (p_open, p_visible, p_selected,
    // ...) reads awkwardly once it's a real Ref wrapper rather than a raw pointer - drop it.
    const isRefRoute = arg.resolved.kind === 'bytes' && origResolved.kind === 'ref'
    const exposedName = renameTo.get(arg.name) ?? arg.name
    const strippedName = isRefRoute && exposedName.startsWith('p_') ? exposedName.slice(2) : exposedName
    const hxName = hxParamName(toCamelCase(strippedName))

    const defaultInfo = translateDefault(f.def.defaults[arg.name] ?? '')
    let hxType: string
    let callExpr: string
    let defaultLiteral: string | null = defaultInfo?.kind === 'literal' ? defaultInfo.text : null

    if (arg.resolved.kind === 'string' && !arg.resolved.mutable) {
      hxType = 'String'
      callExpr = `cstr(${hxName})`
    } else if (isRefRoute && origResolved.kind === 'ref') {
      hxType = REF_WRAPPER_TYPE[origResolved.prim] ?? 'hl.Bytes'
      callExpr = hxName
    } else if (arg.resolved.kind === 'struct' && defaultInfo?.kind === 'structNew') {
      hxType = arg.resolved.name
      callExpr = hxName
      defaultLiteral = 'null'
      preStatements.push(`${hxName} = ${hxName} ?? ${defaultInfo.ctor};`)
    } else {
      hxType = hxParamType(arg.resolved)
      callExpr = hxName
    }

    params.push({ hxName, hxType, defaultLiteral })
    callArgs.push(callExpr)
  }

  // Haxe requires optional (defaulted) params to be a trailing run - a required param can never
  // follow an optional one. cimgui's own C++ signatures always satisfy this, but an EARLIER param can
  // still end up defaulted here while a LATER one doesn't, whenever translateDefault can't parse that
  // later param's own literal (some exotic constant neither it nor numLit recognizes) - dropping
  // every default before the last required param keeps the result always valid Haxe even then, at
  // the cost of losing a few otherwise-translatable defaults in that rare case.
  let stillTrailingOptional = true
  for (let i = params.length - 1; i >= 0; i--) {
    if (params[i].defaultLiteral === null) stillTrailingOptional = false
    if (!stillTrailingOptional) params[i].defaultLiteral = null
  }

  let retType = hxParamType(f.ret) === 'Void' ? 'Void' : hxParamType(f.ret)
  let returnsCoalescedOut: string | null = null
  if (f.outParam) {
    if (f.outParam.kind === 'struct') {
      const hxName = 'hlxOut'
      params.push({ hxName, hxType: f.outParam.name, defaultLiteral: 'null' })
      preStatements.push(`${hxName} = ${hxName} ?? new ${f.outParam.name}();`)
      callArgs.push(hxName)
      retType = f.outParam.name
      returnsCoalescedOut = hxName
    } else {
      // Defensive fallback (no bound function currently has a non-struct outParam) - today's plain
      // out-param style: caller-allocated, required, Void return.
      params.push({ hxName: 'hlxOut', hxType: hxParamType(f.outParam), defaultLiteral: null })
      callArgs.push('hlxOut')
    }
  }

  return {
    implName,
    implLines,
    params,
    preStatements,
    callArgs,
    retType,
    returnsCoalescedOut,
    fallbackPublicName: isFree ? cleanFreeFunctionName(f.def.ov_cimguiname) : f.def.ov_cimguiname,
    groupKey: isFree ? f.def.cimguiname : null,
  }
}

// Scans everything OUTSIDE the two generated marker regions in ImGui.hx's CURRENT (pre-regen)
// content for existing method names (`function someName(`) - these are the hand-written lifecycle
// glue and helpers (init, text, vec2, cstr, ...) that generatedMethodLines below must not collide
// with when assigning a dispatcher's public name. Deliberately a regex, not a real Haxe parse - this
// file's style is consistent enough (one function declaration per `function name(` occurrence) that
// a full parser would be pure overkill.
function collectHandWrittenNames(imguiHxText: string): Set<string> {
  const withoutGenerated = spliceMarked(spliceMarked(imguiHxText, TYPEDEFS_START, TYPEDEFS_END, []), METHODS_START, METHODS_END, [])
  const names = new Set<string>()
  for (const m of withoutGenerated.matchAll(/\bfunction\s+(\w+)\s*\(/g)) names.add(m[1])
  return names
}

function cppLines(): string[] {
  const lines: string[] = []
  lines.push('// GENERATED by native/codegen/generate.mts - do not hand-edit, re-run the generator instead.')
  lines.push('#define HL_NAME(n) imgui_##n')
  lines.push('#include <hl.h>')
  // Matches third_party/cimgui/cimgui.cpp's own include order exactly (real imgui.h/imgui_internal.h
  // first, cimgui.h after, CIMGUI_DEFINE_ENUMS_AND_STRUCTS left undefined) - that's the only
  // configuration cimgui ships a proven-working reference build for, so this generated file rides
  // the same real ImDrawList/ImGuiIO/etc. type declarations rather than cimgui.h's from-scratch
  // pure-C mirror declarations (which are for standalone-C consumers with no access to real imgui.h).
  lines.push('#include "../../third_party/imgui/imgui.h"')
  lines.push('#include "../../third_party/imgui/imgui_internal.h"')
  lines.push('#include "../../third_party/cimgui/cimgui.h"')
  lines.push('')

  function emitOne(f: BoundFunc, args: BoundArg[], exportName: string) {
    const d = f.def
    const cParams = args.map((a) => `${cParamType(a.resolved)} ${a.name}`)
    if (f.outParam) cParams.push(`${cParamType(f.outParam)} hlx_out`)
    const cRet = cParamType(f.ret)

    // Walk the ORIGINAL argument order (not args, which omits params the resolver dropped) so
    // hardcoded literal defaults for dropped params (unsupported-but-defaulted, e.g. InputText's
    // callback/user_data) land back in their correct position in the real call.
    const boundArgsByName = new Map(args.map((a) => [a.name, a]))
    const fullCallArgs: string[] = []
    for (const a of d.argsT) {
      const arg = boundArgsByName.get(a.name)
      if (arg) fullCallArgs.push(callExpr(arg.name, arg.resolved, a.type))
      else if (a.name in d.defaults) fullCallArgs.push(d.defaults[a.name])
    }

    // ov_cimguiname, NOT cimguiname - cimguiname is only the shared group key overloads are filed
    // under in definitions.json; cimgui.h only ever exports the overload-suffixed ov_cimguiname as
    // a real linkable symbol (confirmed by a real MSVC build: "igGetID"/"igCombo"/"igMenuItem"/...
    // all failed as "identifier not found" until this was fixed - they only exist as e.g.
    // igGetID_Str/igCombo_Str/igMenuItem_Bool). Coincidentally identical for functions with exactly
    // one overload (cimguiname === ov_cimguiname there), which is why this went unnoticed until an
    // overloaded one was hit.
    const call = `${d.ov_cimguiname}(${fullCallArgs.join(', ')})`
    lines.push(`HL_PRIM ${cRet} HL_NAME(${exportName})(${cParams.join(', ') || 'void'}) {`)
    if (f.outParam) {
      // Cast to the VALUE type (cParamType's pointer form minus the trailing "*", since we're
      // assigning through the dereferenced hlx_out, not to a pointer) - needed whenever the real
      // return is const-qualified or a differently-named-but-layout-identical type (e.g.
      // "const ImVec4_c" vs our own non-const "ImVec4_c") - confirmed by a real MSVC build error
      // ("conversion loses qualifiers").
      const outValueType = cParamType(f.outParam).replace(/\*$/, '')
      lines.push(`\t*hlx_out = (${outValueType})${call};`)
    } else if (f.ret.kind === 'prim' && f.ret.prim === 'void') {
      lines.push(`\t${call};`)
    } else {
      lines.push(`\treturn (${cRet})${call};`)
    }
    lines.push('}')
    const defineArgs = args.map((a) => cDefineMacro(a.resolved))
    if (f.outParam) defineArgs.push(cDefineMacro(f.outParam))
    lines.push(`DEFINE_PRIM(${cDefineMacro(f.ret)}, ${exportName}, ${defineArgs.join(' ') || '_NO_ARG'});`)
    lines.push('')
  }

  for (const f of bound) {
    emitOne(f, f.args, f.def.ov_cimguiname)
    if (hasRefArg(f)) emitOne(f, toPointerVariantArgs(f.args), pointerVariantName(f))
  }
  return lines
}

// ---------------------------------------------------------------------------
// Emit: hl-imgui/src/imgui/ImGui.hx (spliced) + {Enums,Structs}.hx
// ---------------------------------------------------------------------------

function hxParamType(r: Resolved): string {
  switch (r.kind) {
    case 'prim':
      return PRIM_HX_TYPE[r.prim]
    case 'string':
      return 'hl.Bytes'
    case 'opaque':
      return r.name
    case 'struct':
      return r.name
    case 'ref':
      return `hl.Ref<${PRIM_HX_TYPE[r.prim]}>`
    case 'bytes':
      return 'hl.Bytes'
    case 'unsupported':
      throw new Error('unreachable')
  }
}

function hxDefaultReturn(r: Resolved): string {
  switch (r.kind) {
    case 'prim':
      return r.prim === 'void' ? '' : r.prim === 'bool' ? 'return false;' : r.prim === 'f32' || r.prim === 'f64' ? 'return 0;' : 'return 0;'
    default:
      return 'return null;'
  }
}

// cimgui's own param names (self, in, out, ...) are valid C identifiers but a few collide with
// Haxe keywords. @:hlNative externs bind by POSITION, not name, so renaming a param here for
// Haxe's sake has zero effect on the actual native call - only cosmetic/keyword-safety.
const HAXE_RESERVED = new Set([
  'in', 'out', 'new', 'class', 'var', 'function', 'static', 'default', 'null', 'true', 'false',
  'if', 'else', 'for', 'while', 'do', 'break', 'continue', 'return', 'switch', 'case', 'try',
  'catch', 'throw', 'extends', 'implements', 'import', 'package', 'public', 'private', 'extern',
  'inline', 'override', 'dynamic', 'cast', 'untyped', 'this', 'super', 'enum', 'abstract',
  'interface', 'typedef', 'using', 'macro',
])
function hxParamName(name: string): string {
  return HAXE_RESERVED.has(name) ? `${name}_` : name
}

// A referenced POD struct already has a permanent hand-written import at the top of ImGui.hx
// (ImVec2/ImVec4, used directly in hand-written signatures like `button`'s `size:Vec2`) - only
// emit an import here for one that ISN'T already hand-imported, so regeneration never produces a
// duplicate `import` a reviewer would otherwise have to notice is harmless.
const HAND_IMPORTED_STRUCTS = new Set(['ImVec2', 'ImVec4'])

// Module-level typedefs (opaque handles, plus imports for any POD struct not already hand-imported)
// - spliced in ABOVE the abstract, between TYPEDEFS_START/END. Typedefs can't live inside a class/
// abstract body, so this can't be part of generatedMethodLines() below.
function generatedTypedefLines(): string[] {
  const lines: string[] = []
  // Structs.hx is a sibling MODULE in the same package, not the same file - Haxe doesn't
  // auto-import sibling modules' types (only same-file types see each other implicitly). Each type
  // needs its own import statement by exact name: `import imgui.Structs;` fails outright (Structs.hx
  // has no type literally named "Structs"), and even the `Structs.*` wildcard form only re-exports
  // static members of a type actually named "Structs" (not "every type this module declares") -
  // confirmed empirically, neither resolves anything here.
  for (const name of [...referencedPodStructs].sort()) {
    if (!HAND_IMPORTED_STRUCTS.has(name)) lines.push(`import imgui.Structs.${name};`)
  }
  // One opaque-handle typedef per nonPOD type actually referenced by a bound function's signature
  // (ImDrawList, ImGuiIO, ImFont, ...) - the string must match the C side's _ABSTRACT(name) verbatim,
  // same convention as shader-cache/src/sc/native/Native.hx's `hl.Abstract<"dx_device">`.
  for (const name of [...referencedOpaqueTypes].sort()) {
    lines.push(`typedef ${name} = hl.Abstract<"${name}">;`)
  }
  return lines
}

// The real @:hlNative-bound implementation for one function - always private (see compileDispatcher's
// own doc comment for why: it's only ever called by that function's own public dispatcher, never
// directly by a mod author). Structurally identical to what used to be the ONLY thing this generator
// emitted per function, before dispatchers existed.
function emitImplLines(haxeName: string, args: BoundArg[], exportName: string, f: BoundFunc): string[] {
  const lines: string[] = []
  const params = args.map((a) => `${hxParamName(a.name)}:${hxParamType(a.resolved)}`)
  if (f.outParam) params.push(`hlxOut:${hxParamType(f.outParam)}`)
  const retType = hxParamType(f.ret) === 'Void' ? 'Void' : hxParamType(f.ret)
  lines.push(`\t@:hlNative("imgui", "${exportName}")`)
  lines.push(`\tprivate static function ${haxeName}(${params.join(', ')}):${retType} {`)
  const body = hxDefaultReturn(f.ret)
  if (body) lines.push(`\t\t${body}`)
  lines.push('\t}')
  lines.push('')
  return lines
}

// The bulk binding surface itself - spliced in as members of the abstract, between METHODS_START/
// END. Every bound function gets a private @:hlNative implementation (see emitImplLines) plus a
// public ergonomic dispatcher (see compileDispatcher) - UNLESS a hand-written function already
// claims that dispatcher's name (lifecycle glue like render/newFrame, or a handful of deliberate
// aliases like text()), in which case only the private implementation is emitted and the
// hand-written function remains the sole public entry point, exactly as before this generator could
// build dispatchers itself. Free-function dispatchers that belong to the same cimgui overload group
// (shared `cimguiname`, e.g. igOpenPopup_Str/igOpenPopup_ID) merge into one `overload extern inline`
// group under the group's own clean name when every member's signature is mutually distinguishable
// (see signatureKey) - otherwise each keeps its own individually-suffixed name, same as a
// single-member group. Either way, the ACTUAL native symbol looked up via @:hlNative is never
// renamed by any of this; only Haxe-visible identifiers are, so no native rebuild is ever needed.
function generatedMethodLines(handWrittenNames: Set<string>): string[] {
  const lines: string[] = []
  const usedImplNames = new Set<string>()
  const seenNonMergedPublicNames = new Set<string>()

  const compiled = bound.map((f) => ({ f, d: compileDispatcher(f, usedImplNames) }))

  const groups = new Map<string, typeof compiled>()
  for (const c of compiled) {
    if (c.d.groupKey == null) continue
    if (!groups.has(c.d.groupKey)) groups.set(c.d.groupKey, [])
    groups.get(c.d.groupKey)!.push(c)
  }

  // Every group defaults to the shared, unsuffixed cimguiname-derived name - including a group with
  // only ONE surviving bound member (the overwhelmingly common case: either a real single-overload
  // cimgui function, or one whose sibling overloads were skipped as unsupported, e.g. TreeNode_Str's
  // TreeNode_Ptr sibling) - a lone member never collides with itself, so it always keeps the clean
  // name with no `overload` keyword needed. Only a GENUINE signature collision among 2+ surviving
  // members falls back to each member's own individually-suffixed name instead.
  const sharedName = new Map<(typeof compiled)[number], string>()
  for (const [cimguiname, members] of groups) {
    const keys = members.map((m) => signatureKey(m.d.params))
    if (members.length > 1 && keys.some((k, i) => keys.indexOf(k) !== i)) continue // ambiguous - fall back
    for (const m of members) sharedName.set(m, cleanFreeFunctionName(cimguiname))
  }

  for (const c of compiled) {
    lines.push(...c.d.implLines)

    const group = c.d.groupKey != null ? groups.get(c.d.groupKey)! : null
    const isOverloadGroup = sharedName.has(c) && group !== null && group.length > 1
    const publicName = sharedName.get(c) ?? c.d.fallbackPublicName

    if (handWrittenNames.has(publicName)) continue // hand-written code already owns this name

    if (!isOverloadGroup) {
      if (seenNonMergedPublicNames.has(publicName)) throw new Error(`duplicate generated name: ${JSON.stringify(publicName)}`)
      seenNonMergedPublicNames.add(publicName)
    }

    const modifiers = isOverloadGroup ? 'public static overload extern inline' : 'public static inline'
    const paramsStr = c.d.params.map((p) => `${p.hxName}:${p.hxType}${p.defaultLiteral !== null ? ` = ${p.defaultLiteral}` : ''}`).join(', ')
    const callExpr = `${c.d.implName}(${c.d.callArgs.join(', ')})`
    const simple = c.d.preStatements.length === 0 && c.d.returnsCoalescedOut === null

    if (simple) {
      lines.push(`\t${modifiers} function ${publicName}(${paramsStr}):${c.d.retType}`)
      lines.push(`\t\t${c.d.retType === 'Void' ? `${callExpr};` : `return ${callExpr};`}`)
      lines.push('')
    } else {
      lines.push(`\t${modifiers} function ${publicName}(${paramsStr}):${c.d.retType} {`)
      for (const s of c.d.preStatements) lines.push(`\t\t${s}`)
      if (c.d.returnsCoalescedOut !== null) {
        lines.push(`\t\t${callExpr};`)
        lines.push(`\t\treturn ${c.d.returnsCoalescedOut};`)
      } else {
        lines.push(`\t\t${c.d.retType === 'Void' ? `${callExpr};` : `return ${callExpr};`}`)
      }
      lines.push('\t}')
      lines.push('')
    }
  }
  return lines
}

// Rewrites everything strictly between a start/end marker LINE (both kept verbatim) with `body` -
// everything outside that range (the hand-written parts of ImGui.hx) survives untouched. Throws
// rather than silently no-op-ing if a marker's missing or duplicated - a generator that can't find
// its own splice point should fail loudly, not write nothing or write into the wrong place.
function spliceMarked(text: string, startMarker: string, endMarker: string, body: string[]): string {
  const lines = text.split('\n')
  const startIdx = lines.indexOf(startMarker)
  const endIdx = lines.indexOf(endMarker)
  if (startIdx === -1) throw new Error(`marker not found: ${JSON.stringify(startMarker)}`)
  if (endIdx === -1) throw new Error(`marker not found: ${JSON.stringify(endMarker)}`)
  if (endIdx <= startIdx) throw new Error(`end marker appears before start marker: ${JSON.stringify(startMarker)}`)
  if (lines.indexOf(startMarker, startIdx + 1) !== -1) throw new Error(`duplicate marker: ${JSON.stringify(startMarker)}`)
  return [...lines.slice(0, startIdx + 1), ...body, ...lines.slice(endIdx)].join('\n')
}

function sanitizeEnumMemberName(enumKey: string, memberName: string): string {
  let short = memberName.startsWith(enumKey) ? memberName.slice(enumKey.length) : memberName
  short = short.replace(/^_+/, '').replace(/_+$/, '')
  if (short.length === 0 || /^[0-9]/.test(short)) short = `_${short || memberName}`
  return short
}

function enumsHxLines(): string[] {
  const lines: string[] = []
  lines.push('// GENERATED by native/codegen/generate.mts - do not hand-edit, re-run the generator instead.')
  lines.push('package imgui;')
  lines.push('')
  for (const enumKey of Object.keys(structsAndEnums.enums).sort()) {
    const values = structsAndEnums.enums[enumKey]
    const typeName = enumKey.endsWith('_') ? enumKey.slice(0, -1) : enumKey
    lines.push(`abstract ${typeName}(Int) from Int to Int {`)
    const seen = new Set<string>()
    for (const v of values) {
      const short = sanitizeEnumMemberName(enumKey, v.name)
      if (seen.has(short)) continue
      seen.add(short)
      lines.push(`\tpublic static inline var ${short} = ${v.calc_value};`)
    }
    lines.push('}')
    lines.push('')
  }
  return lines
}

function structsHxLines(): string[] {
  const lines: string[] = []
  lines.push('// GENERATED by native/codegen/generate.mts - do not hand-edit, re-run the generator instead.')
  lines.push('package imgui;')
  lines.push('')
  for (const name of [...referencedPodStructs].sort()) {
    // Guaranteed all-primitive by fullyPrimitiveStructFields - referencedPodStructs only ever
    // gets a name added to it via that same check (see resolveBase's struct-kind branch above).
    const fields = fullyPrimitiveStructFields(name)!
    lines.push('@:struct')
    lines.push(`class ${name} {`)
    for (const field of fields) {
      lines.push(`\tpublic var ${field.name}:${PRIM_HX_TYPE[field.prim]};`)
    }
    lines.push('\tpublic function new() {}')
    lines.push('}')
    lines.push('')
  }
  return lines
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fs.mkdirSync(path.dirname(OUT_CPP), { recursive: true })
fs.mkdirSync(OUT_HX_DIR, { recursive: true })

// referencedOpaqueTypes/referencedPodStructs were already populated above while building `bound` -
// structsHxLines() (called below) depends on that being complete, which it is by construction.
const cpp = cppLines()
const imguiHxBefore = fs.readFileSync(OUT_IMGUI_HX, 'utf8')
const handWrittenNames = collectHandWrittenNames(imguiHxBefore)
const imguiHxTypedefs = generatedTypedefLines()
const imguiHxMethods = generatedMethodLines(handWrittenNames)
const structsHx = structsHxLines()
const enumsHx = enumsHxLines()

fs.writeFileSync(OUT_CPP, cpp.join('\n') + '\n', 'utf8')

const imguiHxAfterTypedefs = spliceMarked(imguiHxBefore, TYPEDEFS_START, TYPEDEFS_END, imguiHxTypedefs)
const imguiHxAfterMethods = spliceMarked(imguiHxAfterTypedefs, METHODS_START, METHODS_END, imguiHxMethods)
fs.writeFileSync(OUT_IMGUI_HX, imguiHxAfterMethods, 'utf8')

fs.writeFileSync(path.join(OUT_HX_DIR, 'Enums.hx'), enumsHx.join('\n') + '\n', 'utf8')
fs.writeFileSync(path.join(OUT_HX_DIR, 'Structs.hx'), structsHx.join('\n') + '\n', 'utf8')

console.log(`Bound ${bound.length} functions.`)
console.log(`Skipped ${skipped.length} functions.`)
console.log(`Referenced opaque handle types: ${referencedOpaqueTypes.size}`)
console.log(`Referenced POD struct types: ${referencedPodStructs.size}`)

const reasonCounts = new Map<string, number>()
for (const s of skipped) {
  const bucket = s.reason.replace(/"[^"]*"/, '"..."')
  reasonCounts.set(bucket, (reasonCounts.get(bucket) ?? 0) + 1)
}
console.log('\nSkip reasons (bucketed):')
for (const [reason, count] of [...reasonCounts.entries()].sort((a, b) => b[1] - a[1])) {
  console.log(`  ${count.toString().padStart(4)}  ${reason}`)
}

fs.writeFileSync(
  path.join(HERE, 'skipped.log'),
  skipped.map((s) => `${s.name}: ${s.reason}`).join('\n') + '\n',
  'utf8',
)
console.log(`\nFull skip list written to ${path.relative(process.cwd(), path.join(HERE, 'skipped.log'))}`)
