#pragma once

#include "../types.h"

// One typedef + one resolved function pointer per real "dx12" native (99 total, including
// get_device - resolved the same way as everything else even though its own stub adds
// device-capture logic on top of the plain forward). Populated once, in LoadDx12Impl, right
// after dx12_original.hdll itself loads. Shared by forwarding.cpp (95 mechanical stubs) and
// intercepts.cpp (the 4 stubs with real cache logic).

typedef dx_device (*Fn_get_device)(void);
typedef void (*Fn_resource_release)(dx_resource);
typedef void (*Fn_resource_set_name)(dx_resource, vbyte *);
typedef int64 (*Fn_resource_get_gpu_virtual_address)(dx_resource);
typedef int64 (*Fn_get_required_intermediate_size)(dx_resource, int, int);
typedef vbyte * (*Fn_resource_map)(dx_resource, int, void *);
typedef void (*Fn_resource_unmap)(dx_resource, int, void *);
typedef dx_resource (*Fn_command_queue_create)(int);
typedef void (*Fn_command_queue_execute_command_list)(dx_resource, dx_resource);
typedef void (*Fn_command_queue_execute_command_lists)(dx_resource, void *, int);
typedef void (*Fn_command_queue_signal)(dx_resource, dx_resource, int64);
typedef void (*Fn_command_queue_wait)(dx_resource, dx_resource, int64);
typedef dx_resource (*Fn_command_allocator_create)(int);
typedef void (*Fn_command_allocator_reset)(dx_resource);
typedef dx_resource (*Fn_command_list_create)(int, dx_resource, dx_resource);
typedef void (*Fn_command_list_close)(dx_resource);
typedef void (*Fn_command_list_execute)(dx_resource);
typedef void (*Fn_command_list_clear_render_target_view)(dx_resource, int64, void *);
typedef void (*Fn_command_list_clear_depth_stencil_view)(dx_resource, int64, int, float, int);
typedef void (*Fn_command_list_reset)(dx_resource, dx_resource, dx_resource);
typedef void (*Fn_command_list_resource_barrier)(dx_resource, void *);
typedef void (*Fn_command_list_resource_barriers)(dx_resource, void *, int);
typedef void (*Fn_command_list_set_pipeline_state)(dx_resource, dx_resource);
typedef void (*Fn_command_list_set_descriptor_heaps)(dx_resource, varray *);
typedef void (*Fn_command_list_copy_buffer_region)(dx_resource, dx_resource, int64, dx_resource, int64, int64);
typedef void (*Fn_command_list_copy_texture_region)(dx_resource, void *, int, int, int, void *, void *);
typedef void (*Fn_command_list_set_graphics_root_signature)(dx_resource, dx_resource);
typedef void (*Fn_command_list_set_graphics_root32_bit_constants)(dx_resource, int, int, vbyte *, int);
typedef void (*Fn_command_list_set_graphics_root_constant_buffer_view)(dx_resource, int, int64);
typedef void (*Fn_command_list_set_graphics_root_descriptor_table)(dx_resource, int, int64);
typedef void (*Fn_command_list_set_graphics_root_shader_resource_view)(dx_resource, int, int64);
typedef void (*Fn_command_list_set_graphics_root_unordered_access_view)(dx_resource, int, int64);
typedef void (*Fn_command_list_ia_set_primitive_topology)(dx_resource, int);
typedef void (*Fn_command_list_ia_set_vertex_buffers)(dx_resource, int, int, void *);
typedef void (*Fn_command_list_ia_set_index_buffer)(dx_resource, void *);
typedef void (*Fn_command_list_draw_instanced)(dx_resource, int, int, int, int);
typedef void (*Fn_command_list_draw_indexed_instanced)(dx_resource, int, int, int, int, int);
typedef void (*Fn_command_list_execute_indirect)(dx_resource, dx_resource, int, dx_resource, int64, dx_resource, int64);
typedef void (*Fn_command_list_om_set_render_targets)(dx_resource, int, vbyte *, int, vbyte *);
typedef void (*Fn_command_list_om_set_stencil_ref)(dx_resource, int);
typedef void (*Fn_command_list_rs_set_viewports)(dx_resource, int, void *);
typedef void (*Fn_command_list_rs_set_scissor_rects)(dx_resource, int, void *);
typedef void (*Fn_command_list_begin_query)(dx_resource, dx_resource, int, int);
typedef void (*Fn_command_list_end_query)(dx_resource, dx_resource, int, int);
typedef void (*Fn_command_list_resolve_query_data)(dx_resource, dx_resource, int, int, int, dx_resource, int64);
typedef void (*Fn_command_list_set_predication)(dx_resource, dx_resource, int64, int);
typedef void (*Fn_command_list_set_compute_root_signature)(dx_resource, dx_resource);
typedef void (*Fn_command_list_set_compute_root32_bit_constants)(dx_resource, int, int, vbyte *, int);
typedef void (*Fn_command_list_set_compute_root_constant_buffer_view)(dx_resource, int, int64);
typedef void (*Fn_command_list_set_compute_root_descriptor_table)(dx_resource, int, int64);
typedef void (*Fn_command_list_set_compute_root_shader_resource_view)(dx_resource, int, int64);
typedef void (*Fn_command_list_set_compute_root_unordered_access_view)(dx_resource, int, int64);
typedef void (*Fn_command_list_dispatch)(dx_resource, int, int, int);
typedef dx_resource (*Fn_fence_create)(int64, int);
typedef int64 (*Fn_fence_get_completed_value)(dx_resource);
typedef void (*Fn_fence_set_event)(dx_resource, int64, dx_event);
typedef dx_event (*Fn_waitevent_create)(bool);
typedef bool (*Fn_waitevent_wait)(dx_event, int);
typedef dx_compiler (*Fn_compiler_create)(void);
typedef vbyte * (*Fn_compiler_compile)(dx_compiler, vbyte *, vbyte *, varray *, int *);
typedef dx_resource (*Fn_descriptor_heap_create)(void *);
typedef int64 (*Fn_descriptor_heap_get_handle)(dx_resource, bool);
typedef dx_resource (*Fn_rootsignature_create)(vbyte *, int);
typedef dx_driver (*Fn_create)(dx_window, int, vbyte *);
typedef dx_adapter (*Fn_get_adapter)(void);
typedef void (*Fn_flush_messages)(void);
typedef void (*Fn_suppress_debug_messages)(void *);
typedef int (*Fn_get_descriptor_handle_increment_size)(int);
typedef dx_resource (*Fn_create_graphics_pipeline_state)(void *);
typedef dx_resource (*Fn_create_compute_pipeline_state)(void *);
typedef vbyte * (*Fn_serialize_root_signature)(void *, int, int *);
typedef dx_resource (*Fn_get_back_buffer)(int);
typedef int (*Fn_get_current_back_buffer_index)(void);
typedef void (*Fn_create_render_target_view)(dx_resource, void *, int64);
typedef void (*Fn_create_depth_stencil_view)(dx_resource, void *, int64);
typedef void (*Fn_create_constant_buffer_view)(void *, int64);
typedef void (*Fn_create_unordered_access_view)(dx_resource, dx_resource, void *, int64);
typedef void (*Fn_create_shader_resource_view)(dx_resource, void *, int64);
typedef dx_resource (*Fn_create_query_heap)(void *);
typedef void (*Fn_get_copyable_footprints)(void *, int, int, int64, void *, vbyte *, vbyte *, vbyte *);
typedef void (*Fn_create_sampler)(void *, int64);
typedef dx_resource (*Fn_create_committed_resource)(void *, int, void *, int, void *);
typedef dx_resource (*Fn_create_command_signature)(void *, dx_resource);
typedef void (*Fn_resize)(int, int, int, int);
typedef bool (*Fn_update_sub_resource)(dx_resource, dx_resource, dx_resource, int64, int, int, void *);
typedef void (*Fn_signal)(dx_resource, int64);
typedef void (*Fn_wait)(dx_resource, int64);
typedef void (*Fn_present)(bool);
typedef void (*Fn_suspend)(void);
typedef void (*Fn_resume)(void);
typedef int (*Fn_get_constant)(int);
typedef void (*Fn_copy_descriptors_simple)(int, int64, int64, int);
typedef void (*Fn_check_feature_support)(int, vbyte *, int);
typedef vbyte * (*Fn_get_device_name)(void);
typedef varray * (*Fn_list_devices)(void);
typedef int64 (*Fn_get_timestamp_frequency)(void);
typedef int64 (*Fn_get_driver_version)(void);
typedef void (*Fn_query_video_memory_info)(int, void *);
// Added by a Farever game update (fn#31078) - takes the game's GPU-crash callback closure as its
// only argument and just forwards it through; this proxy never calls into it itself.
typedef void (*Fn_set_gpu_crash_handler)(vclosure *);

extern Fn_get_device GReal_get_device;
extern Fn_resource_release GReal_resource_release;
extern Fn_resource_set_name GReal_resource_set_name;
extern Fn_resource_get_gpu_virtual_address GReal_resource_get_gpu_virtual_address;
extern Fn_get_required_intermediate_size GReal_get_required_intermediate_size;
extern Fn_resource_map GReal_resource_map;
extern Fn_resource_unmap GReal_resource_unmap;
extern Fn_command_queue_create GReal_command_queue_create;
extern Fn_command_queue_execute_command_list GReal_command_queue_execute_command_list;
extern Fn_command_queue_execute_command_lists GReal_command_queue_execute_command_lists;
extern Fn_command_queue_signal GReal_command_queue_signal;
extern Fn_command_queue_wait GReal_command_queue_wait;
extern Fn_command_allocator_create GReal_command_allocator_create;
extern Fn_command_allocator_reset GReal_command_allocator_reset;
extern Fn_command_list_create GReal_command_list_create;
extern Fn_command_list_close GReal_command_list_close;
extern Fn_command_list_execute GReal_command_list_execute;
extern Fn_command_list_clear_render_target_view GReal_command_list_clear_render_target_view;
extern Fn_command_list_clear_depth_stencil_view GReal_command_list_clear_depth_stencil_view;
extern Fn_command_list_reset GReal_command_list_reset;
extern Fn_command_list_resource_barrier GReal_command_list_resource_barrier;
extern Fn_command_list_resource_barriers GReal_command_list_resource_barriers;
extern Fn_command_list_set_pipeline_state GReal_command_list_set_pipeline_state;
extern Fn_command_list_set_descriptor_heaps GReal_command_list_set_descriptor_heaps;
extern Fn_command_list_copy_buffer_region GReal_command_list_copy_buffer_region;
extern Fn_command_list_copy_texture_region GReal_command_list_copy_texture_region;
extern Fn_command_list_set_graphics_root_signature GReal_command_list_set_graphics_root_signature;
extern Fn_command_list_set_graphics_root32_bit_constants GReal_command_list_set_graphics_root32_bit_constants;
extern Fn_command_list_set_graphics_root_constant_buffer_view GReal_command_list_set_graphics_root_constant_buffer_view;
extern Fn_command_list_set_graphics_root_descriptor_table GReal_command_list_set_graphics_root_descriptor_table;
extern Fn_command_list_set_graphics_root_shader_resource_view GReal_command_list_set_graphics_root_shader_resource_view;
extern Fn_command_list_set_graphics_root_unordered_access_view GReal_command_list_set_graphics_root_unordered_access_view;
extern Fn_command_list_ia_set_primitive_topology GReal_command_list_ia_set_primitive_topology;
extern Fn_command_list_ia_set_vertex_buffers GReal_command_list_ia_set_vertex_buffers;
extern Fn_command_list_ia_set_index_buffer GReal_command_list_ia_set_index_buffer;
extern Fn_command_list_draw_instanced GReal_command_list_draw_instanced;
extern Fn_command_list_draw_indexed_instanced GReal_command_list_draw_indexed_instanced;
extern Fn_command_list_execute_indirect GReal_command_list_execute_indirect;
extern Fn_command_list_om_set_render_targets GReal_command_list_om_set_render_targets;
extern Fn_command_list_om_set_stencil_ref GReal_command_list_om_set_stencil_ref;
extern Fn_command_list_rs_set_viewports GReal_command_list_rs_set_viewports;
extern Fn_command_list_rs_set_scissor_rects GReal_command_list_rs_set_scissor_rects;
extern Fn_command_list_begin_query GReal_command_list_begin_query;
extern Fn_command_list_end_query GReal_command_list_end_query;
extern Fn_command_list_resolve_query_data GReal_command_list_resolve_query_data;
extern Fn_command_list_set_predication GReal_command_list_set_predication;
extern Fn_command_list_set_compute_root_signature GReal_command_list_set_compute_root_signature;
extern Fn_command_list_set_compute_root32_bit_constants GReal_command_list_set_compute_root32_bit_constants;
extern Fn_command_list_set_compute_root_constant_buffer_view GReal_command_list_set_compute_root_constant_buffer_view;
extern Fn_command_list_set_compute_root_descriptor_table GReal_command_list_set_compute_root_descriptor_table;
extern Fn_command_list_set_compute_root_shader_resource_view GReal_command_list_set_compute_root_shader_resource_view;
extern Fn_command_list_set_compute_root_unordered_access_view GReal_command_list_set_compute_root_unordered_access_view;
extern Fn_command_list_dispatch GReal_command_list_dispatch;
extern Fn_fence_create GReal_fence_create;
extern Fn_fence_get_completed_value GReal_fence_get_completed_value;
extern Fn_fence_set_event GReal_fence_set_event;
extern Fn_waitevent_create GReal_waitevent_create;
extern Fn_waitevent_wait GReal_waitevent_wait;
extern Fn_compiler_create GReal_compiler_create;
extern Fn_compiler_compile GReal_compiler_compile;
extern Fn_descriptor_heap_create GReal_descriptor_heap_create;
extern Fn_descriptor_heap_get_handle GReal_descriptor_heap_get_handle;
extern Fn_rootsignature_create GReal_rootsignature_create;
extern Fn_create GReal_create;
extern Fn_get_adapter GReal_get_adapter;
extern Fn_flush_messages GReal_flush_messages;
extern Fn_suppress_debug_messages GReal_suppress_debug_messages;
extern Fn_get_descriptor_handle_increment_size GReal_get_descriptor_handle_increment_size;
extern Fn_create_graphics_pipeline_state GReal_create_graphics_pipeline_state;
extern Fn_create_compute_pipeline_state GReal_create_compute_pipeline_state;
extern Fn_serialize_root_signature GReal_serialize_root_signature;
extern Fn_get_back_buffer GReal_get_back_buffer;
extern Fn_get_current_back_buffer_index GReal_get_current_back_buffer_index;
extern Fn_create_render_target_view GReal_create_render_target_view;
extern Fn_create_depth_stencil_view GReal_create_depth_stencil_view;
extern Fn_create_constant_buffer_view GReal_create_constant_buffer_view;
extern Fn_create_unordered_access_view GReal_create_unordered_access_view;
extern Fn_create_shader_resource_view GReal_create_shader_resource_view;
extern Fn_create_query_heap GReal_create_query_heap;
extern Fn_get_copyable_footprints GReal_get_copyable_footprints;
extern Fn_create_sampler GReal_create_sampler;
extern Fn_create_committed_resource GReal_create_committed_resource;
extern Fn_create_command_signature GReal_create_command_signature;
extern Fn_resize GReal_resize;
extern Fn_update_sub_resource GReal_update_sub_resource;
extern Fn_signal GReal_signal;
extern Fn_wait GReal_wait;
extern Fn_present GReal_present;
extern Fn_suspend GReal_suspend;
extern Fn_resume GReal_resume;
extern Fn_get_constant GReal_get_constant;
extern Fn_copy_descriptors_simple GReal_copy_descriptors_simple;
extern Fn_check_feature_support GReal_check_feature_support;
extern Fn_get_device_name GReal_get_device_name;
extern Fn_list_devices GReal_list_devices;
extern Fn_get_timestamp_frequency GReal_get_timestamp_frequency;
extern Fn_get_driver_version GReal_get_driver_version;
extern Fn_query_video_memory_info GReal_query_video_memory_info;
extern Fn_set_gpu_crash_handler GReal_set_gpu_crash_handler;

// Loads dx12_original.hdll (via GetDx12ImplPath) and resolves all 99 GReal_<name> pointers above
// from its export table.
void LoadDx12Impl(const char *selfDir);
