// GENERATED by native/codegen/generate.mts - do not hand-edit, re-run the generator instead.
package imgui;

abstract ImDrawFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var RoundCornersTopLeft = 16;
	public static inline var RoundCornersTopRight = 32;
	public static inline var RoundCornersBottomLeft = 64;
	public static inline var RoundCornersBottomRight = 128;
	public static inline var RoundCornersNone = 256;
	public static inline var RoundCornersAll = 240;
	public static inline var RoundCornersDefault = 240;
	public static inline var RoundCornersTop = 48;
	public static inline var RoundCornersBottom = 192;
	public static inline var RoundCornersLeft = 80;
	public static inline var RoundCornersRight = 160;
	public static inline var RoundCornersMask = 496;
	public static inline var Closed = 512;
	public static inline var InvalidMask = -2147483633;
}

abstract ImDrawListFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var AntiAliasedLines = 1;
	public static inline var AntiAliasedLinesUseTex = 2;
	public static inline var AntiAliasedFill = 4;
	public static inline var AllowVtxOffset = 8;
	public static inline var TextNoPixelSnap = 16;
}

abstract ImDrawTextFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var CpuFineClip = 1;
	public static inline var WrapKeepBlanks = 2;
	public static inline var StopOnNewLine = 4;
}

abstract ImFontAtlasFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoPowerOfTwoHeight = 1;
	public static inline var NoMouseCursors = 2;
	public static inline var NoBakedLines = 4;
}

abstract ImFontFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoLoadError = 2;
	public static inline var NoLoadGlyphs = 4;
	public static inline var LockBakedSizes = 8;
	public static inline var ImplicitRefSize = 16;
}

abstract ImGuiActivateFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var PreferInput = 1;
	public static inline var PreferTweak = 2;
	public static inline var TryToPreserveState = 4;
	public static inline var FromTabbing = 8;
	public static inline var FromShortcut = 16;
	public static inline var FromFocusApi = 32;
}

abstract ImGuiAxis(Int) from Int to Int {
	public static inline var None = -1;
	public static inline var X = 0;
	public static inline var Y = 1;
}

abstract ImGuiBackendFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var HasGamepad = 1;
	public static inline var HasMouseCursors = 2;
	public static inline var HasSetMousePos = 4;
	public static inline var RendererHasVtxOffset = 8;
	public static inline var RendererHasTextures = 16;
}

abstract ImGuiButtonFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiButtonFlags_PressedOnClick = 16;
	public static inline var ImGuiButtonFlags_PressedOnClickRelease = 32;
	public static inline var ImGuiButtonFlags_PressedOnClickReleaseAnywhere = 64;
	public static inline var ImGuiButtonFlags_PressedOnRelease = 128;
	public static inline var ImGuiButtonFlags_PressedOnDoubleClick = 256;
	public static inline var ImGuiButtonFlags_PressedOnDragDropHold = 512;
	public static inline var ImGuiButtonFlags_FlattenChildren = 2048;
	public static inline var ImGuiButtonFlags_AlignTextBaseLine = 32768;
	public static inline var ImGuiButtonFlags_NoKeyModsAllowed = 65536;
	public static inline var ImGuiButtonFlags_NoHoldingActiveId = 131072;
	public static inline var ImGuiButtonFlags_NoNavFocus = 262144;
	public static inline var ImGuiButtonFlags_NoHoveredOnFocus = 524288;
	public static inline var ImGuiButtonFlags_NoSetKeyOwner = 1048576;
	public static inline var ImGuiButtonFlags_NoTestKeyOwner = 2097152;
	public static inline var ImGuiButtonFlags_NoFocus = 4194304;
	public static inline var ImGuiButtonFlags_PressedOnMask = 1008;
	public static inline var ImGuiButtonFlags_PressedOnDefault = 32;
}

abstract ImGuiButtonFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var MouseButtonLeft = 1;
	public static inline var MouseButtonRight = 2;
	public static inline var MouseButtonMiddle = 4;
	public static inline var MouseButtonMask = 7;
	public static inline var EnableNav = 8;
	public static inline var AllowOverlap = 4096;
}

abstract ImGuiChildFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Borders = 1;
	public static inline var AlwaysUseWindowPadding = 2;
	public static inline var ResizeX = 4;
	public static inline var ResizeY = 8;
	public static inline var AutoResizeX = 16;
	public static inline var AutoResizeY = 32;
	public static inline var AlwaysAutoResize = 64;
	public static inline var FrameStyle = 128;
	public static inline var NavFlattened = 256;
}

abstract ImGuiCol(Int) from Int to Int {
	public static inline var Text = 0;
	public static inline var TextDisabled = 1;
	public static inline var WindowBg = 2;
	public static inline var ChildBg = 3;
	public static inline var PopupBg = 4;
	public static inline var Border = 5;
	public static inline var BorderShadow = 6;
	public static inline var FrameBg = 7;
	public static inline var FrameBgHovered = 8;
	public static inline var FrameBgActive = 9;
	public static inline var TitleBg = 10;
	public static inline var TitleBgActive = 11;
	public static inline var TitleBgCollapsed = 12;
	public static inline var MenuBarBg = 13;
	public static inline var ScrollbarBg = 14;
	public static inline var ScrollbarGrab = 15;
	public static inline var ScrollbarGrabHovered = 16;
	public static inline var ScrollbarGrabActive = 17;
	public static inline var CheckMark = 18;
	public static inline var CheckboxSelectedBg = 19;
	public static inline var SliderGrab = 20;
	public static inline var SliderGrabActive = 21;
	public static inline var Button = 22;
	public static inline var ButtonHovered = 23;
	public static inline var ButtonActive = 24;
	public static inline var Header = 25;
	public static inline var HeaderHovered = 26;
	public static inline var HeaderActive = 27;
	public static inline var Separator = 28;
	public static inline var SeparatorHovered = 29;
	public static inline var SeparatorActive = 30;
	public static inline var ResizeGrip = 31;
	public static inline var ResizeGripHovered = 32;
	public static inline var ResizeGripActive = 33;
	public static inline var InputTextCursor = 34;
	public static inline var TabHovered = 35;
	public static inline var Tab = 36;
	public static inline var TabSelected = 37;
	public static inline var TabSelectedOverline = 38;
	public static inline var TabDimmed = 39;
	public static inline var TabDimmedSelected = 40;
	public static inline var TabDimmedSelectedOverline = 41;
	public static inline var PlotLines = 42;
	public static inline var PlotLinesHovered = 43;
	public static inline var PlotHistogram = 44;
	public static inline var PlotHistogramHovered = 45;
	public static inline var TableHeaderBg = 46;
	public static inline var TableBorderStrong = 47;
	public static inline var TableBorderLight = 48;
	public static inline var TableRowBg = 49;
	public static inline var TableRowBgAlt = 50;
	public static inline var TextLink = 51;
	public static inline var TextSelectedBg = 52;
	public static inline var TreeLines = 53;
	public static inline var DragDropTarget = 54;
	public static inline var DragDropTargetBg = 55;
	public static inline var UnsavedMarker = 56;
	public static inline var NavCursor = 57;
	public static inline var NavWindowingHighlight = 58;
	public static inline var NavWindowingDimBg = 59;
	public static inline var ModalWindowDimBg = 60;
	public static inline var COUNT = 61;
}

abstract ImGuiColorEditFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoAlpha = 2;
	public static inline var NoPicker = 4;
	public static inline var NoOptions = 8;
	public static inline var NoSmallPreview = 16;
	public static inline var NoInputs = 32;
	public static inline var NoTooltip = 64;
	public static inline var NoLabel = 128;
	public static inline var NoSidePreview = 256;
	public static inline var NoDragDrop = 512;
	public static inline var NoBorder = 1024;
	public static inline var NoColorMarkers = 2048;
	public static inline var AlphaOpaque = 4096;
	public static inline var AlphaNoBg = 8192;
	public static inline var AlphaPreviewHalf = 16384;
	public static inline var AlphaBar = 262144;
	public static inline var HDR = 524288;
	public static inline var DisplayRGB = 1048576;
	public static inline var DisplayHSV = 2097152;
	public static inline var DisplayHex = 4194304;
	public static inline var Uint8 = 8388608;
	public static inline var Float = 16777216;
	public static inline var PickerHueBar = 33554432;
	public static inline var PickerHueWheel = 67108864;
	public static inline var PickerNoRotate = 134217728;
	public static inline var InputRGB = 268435456;
	public static inline var InputHSV = 536870912;
	public static inline var DefaultOptions = 311427072;
	public static inline var AlphaMask = 28674;
	public static inline var DisplayMask = 7340032;
	public static inline var DataTypeMask = 25165824;
	public static inline var PickerMask = 100663296;
	public static inline var InputMask = 805306368;
}

abstract ImGuiComboFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiComboFlags_CustomPreview = 1048576;
}

abstract ImGuiComboFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var PopupAlignLeft = 1;
	public static inline var HeightSmall = 2;
	public static inline var HeightRegular = 4;
	public static inline var HeightLarge = 8;
	public static inline var HeightLargest = 16;
	public static inline var NoArrowButton = 32;
	public static inline var NoPreview = 64;
	public static inline var WidthFitPreview = 128;
	public static inline var HeightMask = 30;
}

abstract ImGuiCond(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Always = 1;
	public static inline var Once = 2;
	public static inline var FirstUseEver = 4;
	public static inline var Appearing = 8;
}

abstract ImGuiConfigFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NavEnableKeyboard = 1;
	public static inline var NavEnableGamepad = 2;
	public static inline var NoMouse = 16;
	public static inline var NoMouseCursorChange = 32;
	public static inline var NoKeyboard = 64;
	public static inline var IsSRGB = 1048576;
	public static inline var IsTouchScreen = 2097152;
}

abstract ImGuiContextHookType(Int) from Int to Int {
	public static inline var NewFramePre = 0;
	public static inline var NewFramePost = 1;
	public static inline var EndFramePre = 2;
	public static inline var EndFramePost = 3;
	public static inline var RenderPre = 4;
	public static inline var RenderPost = 5;
	public static inline var Shutdown = 6;
	public static inline var PendingRemoval = 7;
}

abstract ImGuiDataTypePrivate(Int) from Int to Int {
	public static inline var ImGuiDataType_Pointer = 12;
	public static inline var ImGuiDataType_ID = 13;
}

abstract ImGuiDataType(Int) from Int to Int {
	public static inline var S8 = 0;
	public static inline var U8 = 1;
	public static inline var S16 = 2;
	public static inline var U16 = 3;
	public static inline var S32 = 4;
	public static inline var U32 = 5;
	public static inline var S64 = 6;
	public static inline var U64 = 7;
	public static inline var Float = 8;
	public static inline var Double = 9;
	public static inline var Bool = 10;
	public static inline var String = 11;
	public static inline var COUNT = 12;
}

abstract ImGuiDebugLogFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var EventError = 1;
	public static inline var EventActiveId = 2;
	public static inline var EventFocus = 4;
	public static inline var EventPopup = 8;
	public static inline var EventNav = 16;
	public static inline var EventClipper = 32;
	public static inline var EventSelection = 64;
	public static inline var EventIO = 128;
	public static inline var EventFont = 256;
	public static inline var EventInputRouting = 512;
	public static inline var EventDocking = 1024;
	public static inline var EventViewport = 2048;
	public static inline var EventTable = 4096;
	public static inline var EventMask = 8191;
	public static inline var OutputToTTY = 1048576;
	public static inline var OutputToDebugger = 2097152;
	public static inline var OutputToTestEngine = 4194304;
}

abstract ImGuiDir(Int) from Int to Int {
	public static inline var None = -1;
	public static inline var Left = 0;
	public static inline var Right = 1;
	public static inline var Up = 2;
	public static inline var Down = 3;
	public static inline var COUNT = 4;
}

abstract ImGuiDragDropFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var SourceNoPreviewTooltip = 1;
	public static inline var SourceNoDisableHover = 2;
	public static inline var SourceNoHoldToOpenOthers = 4;
	public static inline var SourceAllowNullID = 8;
	public static inline var SourceExtern = 16;
	public static inline var PayloadAutoExpire = 32;
	public static inline var PayloadNoCrossContext = 64;
	public static inline var PayloadNoCrossProcess = 128;
	public static inline var AcceptBeforeDelivery = 1024;
	public static inline var AcceptNoDrawDefaultRect = 2048;
	public static inline var AcceptNoPreviewTooltip = 4096;
	public static inline var AcceptDrawAsHovered = 8192;
	public static inline var AcceptPeekOnly = 3072;
}

abstract ImGuiFocusRequestFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var RestoreFocusedChild = 1;
	public static inline var UnlessBelowModal = 2;
}

abstract ImGuiFocusedFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var ChildWindows = 1;
	public static inline var RootWindow = 2;
	public static inline var AnyWindow = 4;
	public static inline var NoPopupHierarchy = 8;
	public static inline var RootAndChildWindows = 3;
}

abstract ImGuiFreeTypeLoaderFlags(Int) from Int to Int {
	public static inline var NoHinting = 1;
	public static inline var NoAutoHint = 2;
	public static inline var ForceAutoHint = 4;
	public static inline var LightHinting = 8;
	public static inline var MonoHinting = 16;
	public static inline var Bold = 32;
	public static inline var Oblique = 64;
	public static inline var Monochrome = 128;
	public static inline var LoadColor = 256;
	public static inline var Bitmap = 512;
}

abstract ImGuiHoveredFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiHoveredFlags_DelayMask = 245760;
	public static inline var ImGuiHoveredFlags_AllowedMaskForIsWindowHovered = 12463;
	public static inline var ImGuiHoveredFlags_AllowedMaskForIsItemHovered = 262048;
}

abstract ImGuiHoveredFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var ChildWindows = 1;
	public static inline var RootWindow = 2;
	public static inline var AnyWindow = 4;
	public static inline var NoPopupHierarchy = 8;
	public static inline var AllowWhenBlockedByPopup = 32;
	public static inline var AllowWhenBlockedByActiveItem = 128;
	public static inline var AllowWhenOverlappedByItem = 256;
	public static inline var AllowWhenOverlappedByWindow = 512;
	public static inline var AllowWhenDisabled = 1024;
	public static inline var NoNavOverride = 2048;
	public static inline var AllowWhenOverlapped = 768;
	public static inline var RectOnly = 928;
	public static inline var RootAndChildWindows = 3;
	public static inline var ForTooltip = 4096;
	public static inline var Stationary = 8192;
	public static inline var DelayNone = 16384;
	public static inline var DelayShort = 32768;
	public static inline var DelayNormal = 65536;
	public static inline var NoSharedDelay = 131072;
}

abstract ImGuiInputEventType(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var MousePos = 1;
	public static inline var MouseWheel = 2;
	public static inline var MouseButton = 3;
	public static inline var Key = 4;
	public static inline var Text = 5;
	public static inline var Focus = 6;
	public static inline var COUNT = 7;
}

abstract ImGuiInputFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiInputFlags_RepeatRateDefault = 2;
	public static inline var ImGuiInputFlags_RepeatRateNavMove = 4;
	public static inline var ImGuiInputFlags_RepeatRateNavTweak = 8;
	public static inline var ImGuiInputFlags_RepeatUntilRelease = 16;
	public static inline var ImGuiInputFlags_RepeatUntilKeyModsChange = 32;
	public static inline var ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone = 64;
	public static inline var ImGuiInputFlags_RepeatUntilOtherKeyPress = 128;
	public static inline var ImGuiInputFlags_LockThisFrame = 1048576;
	public static inline var ImGuiInputFlags_LockUntilRelease = 2097152;
	public static inline var ImGuiInputFlags_CondHovered = 4194304;
	public static inline var ImGuiInputFlags_CondActive = 8388608;
	public static inline var ImGuiInputFlags_CondDefault = 12582912;
	public static inline var ImGuiInputFlags_RepeatRateMask = 14;
	public static inline var ImGuiInputFlags_RepeatUntilMask = 240;
	public static inline var ImGuiInputFlags_RepeatMask = 255;
	public static inline var ImGuiInputFlags_CondMask = 12582912;
	public static inline var ImGuiInputFlags_RouteTypeMask = 15360;
	public static inline var ImGuiInputFlags_RouteOptionsMask = 245760;
	public static inline var ImGuiInputFlags_SupportedByIsKeyPressed = 255;
	public static inline var ImGuiInputFlags_SupportedByIsMouseClicked = 1;
	public static inline var ImGuiInputFlags_SupportedByShortcut = 261375;
	public static inline var ImGuiInputFlags_SupportedBySetNextItemShortcut = 523519;
	public static inline var ImGuiInputFlags_SupportedBySetKeyOwner = 3145728;
	public static inline var ImGuiInputFlags_SupportedBySetItemKeyOwner = 15728640;
}

abstract ImGuiInputFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Repeat = 1;
	public static inline var RouteActive = 1024;
	public static inline var RouteFocused = 2048;
	public static inline var RouteGlobal = 4096;
	public static inline var RouteAlways = 8192;
	public static inline var RouteOverFocused = 16384;
	public static inline var RouteOverActive = 32768;
	public static inline var RouteUnlessBgFocused = 65536;
	public static inline var RouteFromRootWindow = 131072;
	public static inline var Tooltip = 262144;
}

abstract ImGuiInputSource(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Mouse = 1;
	public static inline var Keyboard = 2;
	public static inline var Gamepad = 3;
	public static inline var COUNT = 4;
}

abstract ImGuiInputTextFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiInputTextFlags_Multiline = 67108864;
	public static inline var ImGuiInputTextFlags_TempInput = 134217728;
	public static inline var ImGuiInputTextFlags_LocalizeDecimalPoint = 268435456;
}

abstract ImGuiInputTextFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var CharsDecimal = 1;
	public static inline var CharsHexadecimal = 2;
	public static inline var CharsScientific = 4;
	public static inline var CharsUppercase = 8;
	public static inline var CharsNoBlank = 16;
	public static inline var AllowTabInput = 32;
	public static inline var EnterReturnsTrue = 64;
	public static inline var EscapeClearsAll = 128;
	public static inline var CtrlEnterForNewLine = 256;
	public static inline var ReadOnly = 512;
	public static inline var Password = 1024;
	public static inline var AlwaysOverwrite = 2048;
	public static inline var AutoSelectAll = 4096;
	public static inline var ParseEmptyRefVal = 8192;
	public static inline var DisplayEmptyRefVal = 16384;
	public static inline var NoHorizontalScroll = 32768;
	public static inline var NoUndoRedo = 65536;
	public static inline var ElideLeft = 131072;
	public static inline var CallbackCompletion = 262144;
	public static inline var CallbackHistory = 524288;
	public static inline var CallbackAlways = 1048576;
	public static inline var CallbackCharFilter = 2097152;
	public static inline var CallbackResize = 4194304;
	public static inline var CallbackEdit = 8388608;
	public static inline var WordWrap = 16777216;
}

abstract ImGuiItemFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiItemFlags_ReadOnly = 2048;
	public static inline var ImGuiItemFlags_MixedValue = 4096;
	public static inline var ImGuiItemFlags_NoWindowHoverableCheck = 8192;
	public static inline var ImGuiItemFlags_AllowOverlap = 16384;
	public static inline var ImGuiItemFlags_NoNavDisableMouseHover = 32768;
	public static inline var ImGuiItemFlags_NoMarkEdited = 65536;
	public static inline var ImGuiItemFlags_NoFocus = 131072;
	public static inline var ImGuiItemFlags_Inputable = 1048576;
	public static inline var ImGuiItemFlags_HasSelectionUserData = 2097152;
	public static inline var ImGuiItemFlags_IsMultiSelect = 4194304;
	public static inline var ImGuiItemFlags_Default = 144;
}

abstract ImGuiItemFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoTabStop = 1;
	public static inline var NoNav = 2;
	public static inline var NoNavDefaultFocus = 4;
	public static inline var ButtonRepeat = 8;
	public static inline var AutoClosePopups = 16;
	public static inline var AllowDuplicateId = 32;
	public static inline var Disabled = 64;
	public static inline var LiveEditOnInputText = 128;
	public static inline var LiveEditOnInputScalar = 256;
	public static inline var LiveEditOnInput = 384;
}

abstract ImGuiItemStatusFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var HoveredRect = 1;
	public static inline var HasDisplayRect = 2;
	public static inline var Edited = 4;
	public static inline var ToggledSelection = 8;
	public static inline var ToggledOpen = 16;
	public static inline var HasDeactivated = 32;
	public static inline var Deactivated = 64;
	public static inline var HoveredWindow = 128;
	public static inline var Visible = 256;
	public static inline var HasClipRect = 512;
	public static inline var HasShortcut = 1024;
	public static inline var EditedInternal = 2048;
}

abstract ImGuiKey(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NamedKey_BEGIN = 512;
	public static inline var Tab = 512;
	public static inline var LeftArrow = 513;
	public static inline var RightArrow = 514;
	public static inline var UpArrow = 515;
	public static inline var DownArrow = 516;
	public static inline var PageUp = 517;
	public static inline var PageDown = 518;
	public static inline var Home = 519;
	public static inline var End = 520;
	public static inline var Insert = 521;
	public static inline var Delete = 522;
	public static inline var Backspace = 523;
	public static inline var Space = 524;
	public static inline var Enter = 525;
	public static inline var Escape = 526;
	public static inline var LeftCtrl = 527;
	public static inline var LeftShift = 528;
	public static inline var LeftAlt = 529;
	public static inline var LeftSuper = 530;
	public static inline var RightCtrl = 531;
	public static inline var RightShift = 532;
	public static inline var RightAlt = 533;
	public static inline var RightSuper = 534;
	public static inline var Menu = 535;
	public static inline var _0 = 536;
	public static inline var _1 = 537;
	public static inline var _2 = 538;
	public static inline var _3 = 539;
	public static inline var _4 = 540;
	public static inline var _5 = 541;
	public static inline var _6 = 542;
	public static inline var _7 = 543;
	public static inline var _8 = 544;
	public static inline var _9 = 545;
	public static inline var A = 546;
	public static inline var B = 547;
	public static inline var C = 548;
	public static inline var D = 549;
	public static inline var E = 550;
	public static inline var F = 551;
	public static inline var G = 552;
	public static inline var H = 553;
	public static inline var I = 554;
	public static inline var J = 555;
	public static inline var K = 556;
	public static inline var L = 557;
	public static inline var M = 558;
	public static inline var N = 559;
	public static inline var O = 560;
	public static inline var P = 561;
	public static inline var Q = 562;
	public static inline var R = 563;
	public static inline var S = 564;
	public static inline var T = 565;
	public static inline var U = 566;
	public static inline var V = 567;
	public static inline var W = 568;
	public static inline var X = 569;
	public static inline var Y = 570;
	public static inline var Z = 571;
	public static inline var F1 = 572;
	public static inline var F2 = 573;
	public static inline var F3 = 574;
	public static inline var F4 = 575;
	public static inline var F5 = 576;
	public static inline var F6 = 577;
	public static inline var F7 = 578;
	public static inline var F8 = 579;
	public static inline var F9 = 580;
	public static inline var F10 = 581;
	public static inline var F11 = 582;
	public static inline var F12 = 583;
	public static inline var F13 = 584;
	public static inline var F14 = 585;
	public static inline var F15 = 586;
	public static inline var F16 = 587;
	public static inline var F17 = 588;
	public static inline var F18 = 589;
	public static inline var F19 = 590;
	public static inline var F20 = 591;
	public static inline var F21 = 592;
	public static inline var F22 = 593;
	public static inline var F23 = 594;
	public static inline var F24 = 595;
	public static inline var Apostrophe = 596;
	public static inline var Comma = 597;
	public static inline var Minus = 598;
	public static inline var Period = 599;
	public static inline var Slash = 600;
	public static inline var Semicolon = 601;
	public static inline var Equal = 602;
	public static inline var LeftBracket = 603;
	public static inline var Backslash = 604;
	public static inline var RightBracket = 605;
	public static inline var GraveAccent = 606;
	public static inline var CapsLock = 607;
	public static inline var ScrollLock = 608;
	public static inline var NumLock = 609;
	public static inline var PrintScreen = 610;
	public static inline var Pause = 611;
	public static inline var Keypad0 = 612;
	public static inline var Keypad1 = 613;
	public static inline var Keypad2 = 614;
	public static inline var Keypad3 = 615;
	public static inline var Keypad4 = 616;
	public static inline var Keypad5 = 617;
	public static inline var Keypad6 = 618;
	public static inline var Keypad7 = 619;
	public static inline var Keypad8 = 620;
	public static inline var Keypad9 = 621;
	public static inline var KeypadDecimal = 622;
	public static inline var KeypadDivide = 623;
	public static inline var KeypadMultiply = 624;
	public static inline var KeypadSubtract = 625;
	public static inline var KeypadAdd = 626;
	public static inline var KeypadEnter = 627;
	public static inline var KeypadEqual = 628;
	public static inline var AppBack = 629;
	public static inline var AppForward = 630;
	public static inline var Oem102 = 631;
	public static inline var GamepadStart = 632;
	public static inline var GamepadBack = 633;
	public static inline var GamepadFaceLeft = 634;
	public static inline var GamepadFaceRight = 635;
	public static inline var GamepadFaceUp = 636;
	public static inline var GamepadFaceDown = 637;
	public static inline var GamepadDpadLeft = 638;
	public static inline var GamepadDpadRight = 639;
	public static inline var GamepadDpadUp = 640;
	public static inline var GamepadDpadDown = 641;
	public static inline var GamepadL1 = 642;
	public static inline var GamepadR1 = 643;
	public static inline var GamepadL2 = 644;
	public static inline var GamepadR2 = 645;
	public static inline var GamepadL3 = 646;
	public static inline var GamepadR3 = 647;
	public static inline var GamepadLStickLeft = 648;
	public static inline var GamepadLStickRight = 649;
	public static inline var GamepadLStickUp = 650;
	public static inline var GamepadLStickDown = 651;
	public static inline var GamepadRStickLeft = 652;
	public static inline var GamepadRStickRight = 653;
	public static inline var GamepadRStickUp = 654;
	public static inline var GamepadRStickDown = 655;
	public static inline var MouseLeft = 656;
	public static inline var MouseRight = 657;
	public static inline var MouseMiddle = 658;
	public static inline var MouseX1 = 659;
	public static inline var MouseX2 = 660;
	public static inline var MouseWheelX = 661;
	public static inline var MouseWheelY = 662;
	public static inline var ReservedForModCtrl = 663;
	public static inline var ReservedForModShift = 664;
	public static inline var ReservedForModAlt = 665;
	public static inline var ReservedForModSuper = 666;
	public static inline var NamedKey_END = 667;
	public static inline var NamedKey_COUNT = 155;
	public static inline var ImGuiMod_None = 0;
	public static inline var ImGuiMod_Ctrl = 4096;
	public static inline var ImGuiMod_Shift = 8192;
	public static inline var ImGuiMod_Alt = 16384;
	public static inline var ImGuiMod_Super = 32768;
	public static inline var ImGuiMod_Mask = 61440;
}

abstract ImGuiLayoutType(Int) from Int to Int {
	public static inline var Horizontal = 0;
	public static inline var Vertical = 1;
}

abstract ImGuiListClipperFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoSetTableRowCounters = 1;
}

abstract ImGuiLocKey(Int) from Int to Int {
	public static inline var VersionStr = 0;
	public static inline var TableSizeOne = 1;
	public static inline var TableSizeAllFit = 2;
	public static inline var TableSizeAllDefault = 3;
	public static inline var TableReset = 4;
	public static inline var TableResetOrder = 5;
	public static inline var TableResetVisibility = 6;
	public static inline var WindowingMainMenuBar = 7;
	public static inline var WindowingPopup = 8;
	public static inline var WindowingUntitled = 9;
	public static inline var OpenLink_s = 10;
	public static inline var CopyLink = 11;
	public static inline var COUNT = 12;
}

abstract ImGuiLogFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var OutputTTY = 1;
	public static inline var OutputFile = 2;
	public static inline var OutputBuffer = 4;
	public static inline var OutputClipboard = 8;
	public static inline var OutputMask = 15;
}

abstract ImGuiMouseButton(Int) from Int to Int {
	public static inline var Left = 0;
	public static inline var Right = 1;
	public static inline var Middle = 2;
	public static inline var COUNT = 5;
}

abstract ImGuiMouseCursor(Int) from Int to Int {
	public static inline var None = -1;
	public static inline var Arrow = 0;
	public static inline var TextInput = 1;
	public static inline var ResizeAll = 2;
	public static inline var ResizeNS = 3;
	public static inline var ResizeEW = 4;
	public static inline var ResizeNESW = 5;
	public static inline var ResizeNWSE = 6;
	public static inline var Hand = 7;
	public static inline var Wait = 8;
	public static inline var Progress = 9;
	public static inline var NotAllowed = 10;
	public static inline var COUNT = 11;
}

abstract ImGuiMouseSource(Int) from Int to Int {
	public static inline var Mouse = 0;
	public static inline var TouchScreen = 1;
	public static inline var Pen = 2;
	public static inline var COUNT = 3;
}

abstract ImGuiMultiSelectFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var SingleSelect = 1;
	public static inline var NoSelectAll = 2;
	public static inline var NoRangeSelect = 4;
	public static inline var NoAutoSelect = 8;
	public static inline var NoAutoClear = 16;
	public static inline var NoAutoClearOnReselect = 32;
	public static inline var BoxSelect1d = 64;
	public static inline var BoxSelect2d = 128;
	public static inline var BoxSelectNoScroll = 256;
	public static inline var ClearOnEscape = 512;
	public static inline var ClearOnClickVoid = 1024;
	public static inline var ScopeWindow = 2048;
	public static inline var ScopeRect = 4096;
	public static inline var SelectOnAuto = 8192;
	public static inline var SelectOnClickAlways = 16384;
	public static inline var SelectOnClickRelease = 32768;
	public static inline var NavWrapX = 65536;
	public static inline var NoSelectOnRightClick = 131072;
	public static inline var SelectOnMask = 57344;
	public static inline var CheckboxMode = 1048576;
}

abstract ImGuiNavLayer(Int) from Int to Int {
	public static inline var Main = 0;
	public static inline var Menu = 1;
	public static inline var COUNT = 2;
}

abstract ImGuiNavMoveFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var LoopX = 1;
	public static inline var LoopY = 2;
	public static inline var WrapX = 4;
	public static inline var WrapY = 8;
	public static inline var WrapMask = 15;
	public static inline var AllowCurrentNavId = 16;
	public static inline var AlsoScoreVisibleSet = 32;
	public static inline var ScrollToEdgeY = 64;
	public static inline var Forwarded = 128;
	public static inline var DebugNoResult = 256;
	public static inline var FocusApi = 512;
	public static inline var IsTabbing = 1024;
	public static inline var IsPageMove = 2048;
	public static inline var Activate = 4096;
	public static inline var NoSelect = 8192;
	public static inline var NoSetNavCursorVisible = 16384;
	public static inline var NoClearActiveId = 32768;
}

abstract ImGuiNavRenderCursorFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Compact = 2;
	public static inline var AlwaysDraw = 4;
}

abstract ImGuiNextItemDataFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var HasWidth = 1;
	public static inline var HasOpen = 2;
	public static inline var HasShortcut = 4;
	public static inline var HasRefVal = 8;
	public static inline var HasStorageID = 16;
	public static inline var HasColorMarker = 32;
}

abstract ImGuiNextWindowDataFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var HasPos = 1;
	public static inline var HasSize = 2;
	public static inline var HasContentSize = 4;
	public static inline var HasCollapsed = 8;
	public static inline var HasSizeConstraint = 16;
	public static inline var HasFocus = 32;
	public static inline var HasBgAlpha = 64;
	public static inline var HasScroll = 128;
	public static inline var HasWindowFlags = 256;
	public static inline var HasChildFlags = 512;
	public static inline var HasRefreshPolicy = 1024;
}

abstract ImGuiOldColumnFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoBorder = 1;
	public static inline var NoResize = 2;
	public static inline var NoPreserveWidths = 4;
	public static inline var NoForceWithinWindow = 8;
	public static inline var GrowParentContentsSize = 16;
}

abstract ImGuiPlotType(Int) from Int to Int {
	public static inline var Lines = 0;
	public static inline var Histogram = 1;
}

abstract ImGuiPopupFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var MouseButtonLeft = 4;
	public static inline var MouseButtonRight = 8;
	public static inline var MouseButtonMiddle = 12;
	public static inline var NoReopen = 32;
	public static inline var NoOpenOverExistingPopup = 128;
	public static inline var NoOpenOverItems = 256;
	public static inline var AnyPopupId = 1024;
	public static inline var AnyPopupLevel = 2048;
	public static inline var AnyPopup = 3072;
	public static inline var MouseButtonShift = 2;
	public static inline var MouseButtonMask = 12;
	public static inline var InvalidMask = 3;
}

abstract ImGuiPopupPositionPolicy(Int) from Int to Int {
	public static inline var Default = 0;
	public static inline var ComboBox = 1;
	public static inline var Tooltip = 2;
}

abstract ImGuiScrollFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var KeepVisibleEdgeX = 1;
	public static inline var KeepVisibleEdgeY = 2;
	public static inline var KeepVisibleCenterX = 4;
	public static inline var KeepVisibleCenterY = 8;
	public static inline var AlwaysCenterX = 16;
	public static inline var AlwaysCenterY = 32;
	public static inline var NoScrollParent = 64;
	public static inline var MaskX = 21;
	public static inline var MaskY = 42;
}

abstract ImGuiSelectableFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiSelectableFlags_NoHoldingActiveID = 1048576;
	public static inline var ImGuiSelectableFlags_SelectOnClick = 4194304;
	public static inline var ImGuiSelectableFlags_SelectOnRelease = 8388608;
	public static inline var ImGuiSelectableFlags_SpanAvailWidth = 16777216;
	public static inline var ImGuiSelectableFlags_SetNavIdOnHover = 33554432;
	public static inline var ImGuiSelectableFlags_NoPadWithHalfSpacing = 67108864;
	public static inline var ImGuiSelectableFlags_NoSetKeyOwner = 134217728;
}

abstract ImGuiSelectableFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoAutoClosePopups = 1;
	public static inline var SpanAllColumns = 2;
	public static inline var AllowDoubleClick = 4;
	public static inline var Disabled = 8;
	public static inline var AllowOverlap = 16;
	public static inline var Highlight = 32;
	public static inline var SelectOnNav = 64;
}

abstract ImGuiSelectionRequestType(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var SetAll = 1;
	public static inline var SetRange = 2;
}

abstract ImGuiSeparatorFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Horizontal = 1;
	public static inline var Vertical = 2;
	public static inline var SpanAllColumns = 4;
}

abstract ImGuiSliderFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiSliderFlags_Vertical = 1048576;
	public static inline var ImGuiSliderFlags_ReadOnly = 2097152;
}

abstract ImGuiSliderFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Logarithmic = 32;
	public static inline var NoRoundToFormat = 64;
	public static inline var NoInput = 128;
	public static inline var WrapAround = 256;
	public static inline var ClampOnInput = 512;
	public static inline var ClampZeroRange = 1024;
	public static inline var NoSpeedTweaks = 2048;
	public static inline var ColorMarkers = 4096;
	public static inline var AlwaysClamp = 1536;
	public static inline var InvalidMask = 1879048207;
}

abstract ImGuiSortDirection(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Ascending = 1;
	public static inline var Descending = 2;
}

abstract ImGuiStyleVar(Int) from Int to Int {
	public static inline var Alpha = 0;
	public static inline var DisabledAlpha = 1;
	public static inline var WindowPadding = 2;
	public static inline var WindowRounding = 3;
	public static inline var WindowBorderSize = 4;
	public static inline var WindowMinSize = 5;
	public static inline var WindowTitleAlign = 6;
	public static inline var ChildRounding = 7;
	public static inline var ChildBorderSize = 8;
	public static inline var PopupRounding = 9;
	public static inline var PopupBorderSize = 10;
	public static inline var FramePadding = 11;
	public static inline var FrameRounding = 12;
	public static inline var FrameBorderSize = 13;
	public static inline var ItemSpacing = 14;
	public static inline var ItemInnerSpacing = 15;
	public static inline var IndentSpacing = 16;
	public static inline var CellPadding = 17;
	public static inline var ScrollbarSize = 18;
	public static inline var ScrollbarRounding = 19;
	public static inline var ScrollbarPadding = 20;
	public static inline var GrabMinSize = 21;
	public static inline var GrabRounding = 22;
	public static inline var ImageRounding = 23;
	public static inline var ImageBorderSize = 24;
	public static inline var TabRounding = 25;
	public static inline var TabBorderSize = 26;
	public static inline var TabMinWidthBase = 27;
	public static inline var TabMinWidthShrink = 28;
	public static inline var TabBarBorderSize = 29;
	public static inline var TabBarOverlineSize = 30;
	public static inline var TableAngledHeadersAngle = 31;
	public static inline var TableAngledHeadersTextAlign = 32;
	public static inline var TreeLinesSize = 33;
	public static inline var TreeLinesRounding = 34;
	public static inline var MenuItemRounding = 35;
	public static inline var SelectableRounding = 36;
	public static inline var DragDropTargetRounding = 37;
	public static inline var ButtonTextAlign = 38;
	public static inline var SelectableTextAlign = 39;
	public static inline var SeparatorSize = 40;
	public static inline var SeparatorTextBorderSize = 41;
	public static inline var SeparatorTextAlign = 42;
	public static inline var SeparatorTextPadding = 43;
	public static inline var COUNT = 44;
}

abstract ImGuiTabBarFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiTabBarFlags_DockNode = 1048576;
	public static inline var ImGuiTabBarFlags_IsFocused = 2097152;
	public static inline var ImGuiTabBarFlags_SaveSettings = 4194304;
}

abstract ImGuiTabBarFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Reorderable = 1;
	public static inline var AutoSelectNewTabs = 2;
	public static inline var TabListPopupButton = 4;
	public static inline var NoCloseWithMiddleMouseButton = 8;
	public static inline var NoTabListScrollingButtons = 16;
	public static inline var NoTooltip = 32;
	public static inline var DrawSelectedOverline = 64;
	public static inline var FittingPolicyMixed = 128;
	public static inline var FittingPolicyShrink = 256;
	public static inline var FittingPolicyScroll = 512;
	public static inline var FittingPolicyMask = 896;
	public static inline var FittingPolicyDefault = 128;
}

abstract ImGuiTabItemFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiTabItemFlags_SectionMask = 192;
	public static inline var ImGuiTabItemFlags_NoCloseButton = 1048576;
	public static inline var ImGuiTabItemFlags_Button = 2097152;
	public static inline var ImGuiTabItemFlags_Invisible = 4194304;
}

abstract ImGuiTabItemFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var UnsavedDocument = 1;
	public static inline var SetSelected = 2;
	public static inline var NoCloseWithMiddleMouseButton = 4;
	public static inline var NoPushId = 8;
	public static inline var NoTooltip = 16;
	public static inline var NoReorder = 32;
	public static inline var Leading = 64;
	public static inline var Trailing = 128;
	public static inline var NoAssumedClosure = 256;
}

abstract ImGuiTableBgTarget(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var RowBg0 = 1;
	public static inline var RowBg1 = 2;
	public static inline var CellBg = 3;
}

abstract ImGuiTableColumnFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Disabled = 1;
	public static inline var DefaultHide = 2;
	public static inline var DefaultSort = 4;
	public static inline var WidthStretch = 8;
	public static inline var WidthFixed = 16;
	public static inline var NoResize = 32;
	public static inline var NoReorder = 64;
	public static inline var NoHide = 128;
	public static inline var NoClip = 256;
	public static inline var NoSort = 512;
	public static inline var NoSortAscending = 1024;
	public static inline var NoSortDescending = 2048;
	public static inline var NoHeaderLabel = 4096;
	public static inline var NoHeaderWidth = 8192;
	public static inline var PreferSortAscending = 16384;
	public static inline var PreferSortDescending = 32768;
	public static inline var IndentEnable = 65536;
	public static inline var IndentDisable = 131072;
	public static inline var AngledHeader = 262144;
	public static inline var IsEnabled = 16777216;
	public static inline var IsVisible = 33554432;
	public static inline var IsSorted = 67108864;
	public static inline var IsHovered = 134217728;
	public static inline var WidthMask = 24;
	public static inline var IndentMask = 196608;
	public static inline var StatusMask = 251658240;
	public static inline var NoDirectResize = 1073741824;
}

abstract ImGuiTableFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Resizable = 1;
	public static inline var Reorderable = 2;
	public static inline var Hideable = 4;
	public static inline var Sortable = 8;
	public static inline var NoSavedSettings = 16;
	public static inline var ContextMenuInBody = 32;
	public static inline var RowBg = 64;
	public static inline var BordersInnerH = 128;
	public static inline var BordersOuterH = 256;
	public static inline var BordersInnerV = 512;
	public static inline var BordersOuterV = 1024;
	public static inline var BordersH = 384;
	public static inline var BordersV = 1536;
	public static inline var BordersInner = 640;
	public static inline var BordersOuter = 1280;
	public static inline var Borders = 1920;
	public static inline var NoBordersInBody = 2048;
	public static inline var NoBordersInBodyUntilResize = 4096;
	public static inline var SizingFixedFit = 8192;
	public static inline var SizingFixedSame = 16384;
	public static inline var SizingStretchProp = 24576;
	public static inline var SizingStretchSame = 32768;
	public static inline var NoHostExtendX = 65536;
	public static inline var NoHostExtendY = 131072;
	public static inline var NoKeepColumnsVisible = 262144;
	public static inline var PreciseWidths = 524288;
	public static inline var NoClip = 1048576;
	public static inline var PadOuterX = 2097152;
	public static inline var NoPadOuterX = 4194304;
	public static inline var NoPadInnerX = 8388608;
	public static inline var ScrollX = 16777216;
	public static inline var ScrollY = 33554432;
	public static inline var SortMulti = 67108864;
	public static inline var SortTristate = 134217728;
	public static inline var HighlightHoveredColumn = 268435456;
	public static inline var SizingMask = 57344;
}

abstract ImGuiTableRowFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Headers = 1;
}

abstract ImGuiTextFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoWidthForLargeClippedText = 1;
}

abstract ImGuiTooltipFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var OverridePrevious = 2;
}

abstract ImGuiTreeNodeFlagsPrivate(Int) from Int to Int {
	public static inline var ImGuiTreeNodeFlags_NoNavFocus = 134217728;
	public static inline var ImGuiTreeNodeFlags_ClipLabelForTrailingButton = 268435456;
	public static inline var ImGuiTreeNodeFlags_UpsideDownArrow = 536870912;
	public static inline var ImGuiTreeNodeFlags_OpenOnMask = 192;
	public static inline var ImGuiTreeNodeFlags_DrawLinesMask = 1835008;
}

abstract ImGuiTreeNodeFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Selected = 1;
	public static inline var Framed = 2;
	public static inline var AllowOverlap = 4;
	public static inline var NoTreePushOnOpen = 8;
	public static inline var NoAutoOpenOnLog = 16;
	public static inline var DefaultOpen = 32;
	public static inline var OpenOnDoubleClick = 64;
	public static inline var OpenOnArrow = 128;
	public static inline var Leaf = 256;
	public static inline var Bullet = 512;
	public static inline var FramePadding = 1024;
	public static inline var SpanAvailWidth = 2048;
	public static inline var SpanFullWidth = 4096;
	public static inline var SpanLabelWidth = 8192;
	public static inline var SpanAllColumns = 16384;
	public static inline var LabelSpanAllColumns = 32768;
	public static inline var NavLeftJumpsToParent = 131072;
	public static inline var CollapsingHeader = 26;
	public static inline var DrawLinesNone = 262144;
	public static inline var DrawLinesFull = 524288;
	public static inline var DrawLinesToNodes = 1048576;
}

abstract ImGuiTypingSelectFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var AllowBackspace = 1;
	public static inline var AllowSingleCharMode = 2;
}

abstract ImGuiViewportFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var IsPlatformWindow = 1;
	public static inline var IsPlatformMonitor = 2;
	public static inline var OwnedByApp = 4;
}

abstract ImGuiWindowBgClickFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var Move = 1;
}

abstract ImGuiWindowFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var NoTitleBar = 1;
	public static inline var NoResize = 2;
	public static inline var NoMove = 4;
	public static inline var NoScrollbar = 8;
	public static inline var NoScrollWithMouse = 16;
	public static inline var NoCollapse = 32;
	public static inline var AlwaysAutoResize = 64;
	public static inline var NoBackground = 128;
	public static inline var NoSavedSettings = 256;
	public static inline var NoMouseInputs = 512;
	public static inline var MenuBar = 1024;
	public static inline var HorizontalScrollbar = 2048;
	public static inline var NoFocusOnAppearing = 4096;
	public static inline var NoBringToFrontOnFocus = 8192;
	public static inline var AlwaysVerticalScrollbar = 16384;
	public static inline var AlwaysHorizontalScrollbar = 32768;
	public static inline var NoNavInputs = 65536;
	public static inline var NoNavFocus = 131072;
	public static inline var UnsavedDocument = 262144;
	public static inline var NoNav = 196608;
	public static inline var NoDecoration = 43;
	public static inline var NoInputs = 197120;
	public static inline var ChildWindow = 16777216;
	public static inline var Tooltip = 33554432;
	public static inline var Popup = 67108864;
	public static inline var Modal = 134217728;
	public static inline var ChildMenu = 268435456;
}

abstract ImGuiWindowRefreshFlags(Int) from Int to Int {
	public static inline var None = 0;
	public static inline var TryToAvoidRefresh = 1;
	public static inline var RefreshOnHover = 2;
	public static inline var RefreshOnFocus = 4;
}

abstract ImTextureFormat(Int) from Int to Int {
	public static inline var RGBA32 = 0;
	public static inline var Alpha8 = 1;
}

abstract ImTextureStatus(Int) from Int to Int {
	public static inline var OK = 0;
	public static inline var Destroyed = 1;
	public static inline var WantCreate = 2;
	public static inline var WantUpdates = 3;
	public static inline var WantDestroy = 4;
}

abstract ImWcharClass(Int) from Int to Int {
	public static inline var Blank = 0;
	public static inline var Punct = 1;
	public static inline var Other = 2;
}

