// GENERATED by native/codegen/generate.mts - do not hand-edit, re-run the generator instead.
package imgui;

@:struct
class ImVec2 {
	public var x:Single;
	public var y:Single;
	public function new(x:Single = 0, y:Single = 0) {
		this.x = x;
		this.y = y;
	}
}

@:struct
class ImVec4 {
	public var x:Single;
	public var y:Single;
	public var z:Single;
	public var w:Single;
	public function new(x:Single = 0, y:Single = 0, z:Single = 0, w:Single = 0) {
		this.x = x;
		this.y = y;
		this.z = z;
		this.w = w;
	}
}
