// GENERATED by native/codegen/generate.mts - do not hand-edit, re-run the generator instead.
package imgui;

@:struct
class ImVec2 {
	public var x:Single;
	public var y:Single;
	public function new() {}
}

@:struct
class ImVec4 {
	public var x:Single;
	public var y:Single;
	public var z:Single;
	public var w:Single;
	public function new() {}
}

